In [1]:
import os 
import json
import random
import pickle as pk
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv
from typing import List
from typing import Literal
import base64
from pydantic import BaseModel, Field

In [2]:
load_dotenv()

True

In [3]:
ASSOCIATION_DIR = os.getenv("ASSOCIATION_DIR")
TABLE_DIR = os.getenv("TABLE_DIR")
OPENAI_KEY = os.getenv("OPENAI_KEY")
FINAL_DATASET_IMAGES = os.getenv("FINAL_DATASET_IMAGES")
CRITERIA_EXTRACTION_DIR = os.getenv("CRITERIA_EXTRACTION_DIR")
QUESTIONS_MULTIMODALQA_TRAINING = os.getenv("QUESTIONS_MULTIMODALQA_TRAINING")
selected_questions = pk.load(open("/Users/emanuelemezzi/PycharmProjects/LEGuidance/scripts/selected_questions.pk", "rb"))

In [4]:
selected_questions

['question_3158.json',
 'question_13163.json',
 'question_10777.json',
 'question_6283.json',
 'question_17285.json',
 'question_16529.json',
 'question_16079.json',
 'question_13905.json',
 'question_6182.json',
 'question_12981.json',
 'question_4386.json',
 'question_6267.json',
 'question_22612.json',
 'question_12708.json',
 'question_23299.json',
 'question_19947.json',
 'question_11084.json',
 'question_11050.json',
 'question_12782.json',
 'question_15982.json',
 'question_16292.json',
 'question_21505.json',
 'question_23629.json',
 'question_11031.json',
 'question_22880.json',
 'question_15684.json',
 'question_5474.json',
 'question_3396.json',
 'question_4979.json',
 'question_9685.json',
 'question_19913.json',
 'question_16006.json',
 'question_20380.json',
 'question_23275.json',
 'question_17301.json',
 'question_7986.json',
 'question_10149.json',
 'question_6683.json',
 'question_7864.json',
 'question_14480.json',
 'question_493.json',
 'question_964.json',
 'question_18511.json',
 'question_9090.json',
 'question_14374.json',
 'question_15968.json',
 'question_6877.json',
 'question_18429.json',
 'question_9815.json',
 'question_12768.json',
 'question_19183.json',
 'question_12860.json',
 'question_18887.json',
 'question_1857.json',
 'question_23654.json',
 'question_16920.json',
 'question_788.json',
 'question_11549.json',
 'question_5918.json',
 'question_20618.json',
 'question_22414.json',
 'question_13372.json',
 'question_19177.json',
 'question_12394.json',
 'question_22698.json',
 'question_17617.json',
 'question_289.json',
 'question_2588.json',
 'question_18929.json',
 'question_23040.json',
 'question_15551.json',
 'question_5019.json',
 'question_12173.json',
 'question_1159.json',
 'question_3903.json',
 'question_16136.json',
 'question_6994.json',
 'question_17554.json',
 'question_12430.json',
 'question_9575.json',
 'question_12940.json',
 'question_8776.json',
 'question_8960.json',
 'question_20497.json',
 'question_3048.json',
 'question_19045.json',
 'question_14611.json',
 'question_1913.json',
 'question_18823.json',
 'question_15841.json',
 'question_4240.json',
 'question_17002.json',
 'question_932.json',
 'question_4544.json',
 'question_3344.json',
 'question_12273.json',
 'question_23812.json',
 'question_7840.json',
 'question_14821.json',
 'question_2239.json',
 'question_5890.json',
 'question_9873.json',
 'question_14676.json',
 'question_20696.json',
 'question_19180.json',
 'question_17079.json',
 'question_3207.json',
 'question_4696.json',
 'question_22817.json',
 'question_160.json',
 'question_459.json',
 'question_18235.json',
 'question_6920.json',
 'question_7038.json',
 'question_11972.json',
 'question_16160.json',
 'question_9636.json',
 'question_18086.json',
 'question_1950.json',
 'question_17044.json',
 'question_12133.json',
 'question_15886.json',
 'question_22971.json',
 'question_5644.json',
 'question_18051.json',
 'question_15890.json',
 'question_3635.json',
 'question_21380.json',
 'question_19430.json',
 'question_3245.json',
 'question_20599.json',
 'question_1398.json',
 'question_16962.json',
 'question_9844.json',
 'question_16571.json',
 'question_6368.json',
 'question_947.json',
 'question_22476.json',
 'question_16885.json',
 'question_6452.json',
 'question_23214.json',
 'question_20017.json',
 'question_23172.json',
 'question_1945.json',
 'question_8305.json',
 'question_7245.json',
 'question_13865.json',
 'question_21593.json',
 'question_21266.json',
 'question_12767.json',
 'question_11645.json',
 'question_13151.json',
 'question_14286.json',
 'question_285.json',
 'question_9029.json',
 'question_4445.json',
 'question_9009.json',
 'question_23412.json',
 'question_1212.json',
 'question_19254.json',
 'question_19184.json',
 'question_6126.json',
 'question_20760.json',
 'question_22165.json',
 'question_16688.json',
 'question_22750.json',
 'question_10364.json',
 'question_6164.json',
 'question_5754.json',
 'question_13182.json',
 'question_4521.json',
 'question_852.json',
 'question_7735.json',
 'question_3208.json',
 'question_8971.json',
 'question_9962.json',
 'question_8358.json',
 'question_20205.json',
 'question_14411.json',
 'question_9055.json',
 'question_10067.json',
 'question_6580.json',
 'question_21430.json',
 'question_14980.json',
 'question_21528.json',
 'question_13075.json',
 'question_2733.json',
 'question_17724.json',
 'question_9976.json',
 'question_5108.json',
 'question_7442.json',
 'question_9458.json',
 'question_6227.json',
 'question_19136.json',
 'question_146.json',
 'question_22495.json',
 'question_22297.json',
 'question_10007.json',
 'question_23507.json',
 'question_18232.json',
 'question_21216.json',
 'question_10584.json',
 'question_9369.json',
 'question_18957.json',
 'question_17906.json',
 'question_16449.json',
 'question_12028.json',
 'question_16460.json',
 'question_7112.json',
 'question_8401.json',
 'question_12634.json',
 'question_21155.json',
 'question_12146.json',
 'question_22369.json',
 'question_13419.json',
 'question_13485.json',
 'question_3870.json',
 'question_20928.json',
 'question_22663.json',
 'question_1472.json',
 'question_6671.json',
 'question_22154.json',
 'question_23789.json',
 'question_19986.json',
 'question_6943.json',
 'question_4885.json',
 'question_15714.json',
 'question_17989.json',
 'question_6467.json',
 'question_9344.json',
 'question_497.json',
 'question_20257.json',
 'question_21717.json',
 'question_20438.json',
 'question_13309.json',
 'question_16627.json',
 'question_16096.json',
 'question_6092.json',
 'question_18458.json',
 'question_10688.json',
 'question_23265.json',
 'question_22763.json',
 'question_16171.json',
 'question_3511.json',
 'question_9163.json',
 'question_10192.json',
 'question_12236.json',
 'question_2964.json',
 'question_12050.json',
 'question_7036.json',
 'question_12140.json',
 'question_7010.json',
 'question_18280.json',
 'question_3328.json',
 'question_21662.json',
 'question_16417.json',
 'question_17303.json',
 'question_4451.json',
 'question_15952.json',
 'question_4075.json',
 'question_13659.json',
 'question_22977.json',
 'question_23035.json',
 'question_20897.json',
 'question_16472.json',
 'question_2958.json',
 'question_19577.json',
 'question_15480.json',
 'question_12802.json',
 'question_8764.json',
 'question_20181.json',
 'question_18801.json',
 'question_4231.json',
 'question_19662.json',
 'question_20757.json',
 'question_11905.json',
 'question_12873.json',
 'question_12072.json',
 'question_19549.json',
 'question_18499.json',
 'question_13147.json',
 'question_16644.json',
 'question_8276.json',
 'question_2748.json',
 'question_574.json',
 'question_9095.json',
 'question_13947.json',
 'question_6163.json',
 'question_15164.json',
 'question_3072.json',
 'question_7362.json',
 'question_16646.json',
 'question_12329.json',
 'question_20315.json',
 'question_2268.json',
 'question_2552.json',
 'question_11848.json',
 'question_22532.json',
 'question_10407.json',
 'question_9629.json',
 'question_16413.json',
 'question_14731.json',
 'question_6184.json',
 'question_3059.json',
 'question_21039.json',
 'question_15927.json',
 'question_6987.json',
 'question_3317.json',
 'question_14705.json',
 'question_7351.json',
 'question_10038.json',
 'question_19340.json',
 'question_4253.json',
 'question_20519.json',
 'question_17451.json',
 'question_2649.json',
 'question_22815.json',
 'question_21177.json',
 'question_14362.json',
 'question_2421.json',
 'question_17685.json',
 'question_15977.json',
 'question_4621.json',
 'question_22573.json',
 'question_2510.json',
 'question_18040.json',
 'question_11991.json',
 'question_23468.json',
 'question_21001.json',
 'question_21435.json',
 'question_4839.json',
 'question_5308.json',
 'question_22974.json',
 'question_21573.json',
 'question_12471.json',
 'question_15336.json',
 'question_5831.json',
 'question_6707.json',
 'question_16362.json',
 'question_19555.json',
 'question_1329.json',
 'question_666.json',
 'question_1138.json',
 'question_12523.json',
 'question_9202.json',
 'question_21851.json',
 'question_8061.json',
 'question_16875.json',
 'question_15787.json',
 'question_22976.json',
 'question_16446.json',
 'question_23171.json',
 'question_6853.json',
 'question_13629.json',
 'question_17804.json',
 'question_20590.json',
 'question_4314.json',
 'question_12277.json',
 'question_10295.json',
 'question_669.json',
 'question_12919.json',
 'question_12286.json',
 'question_9094.json',
 'question_21515.json',
 'question_2261.json',
 'question_2986.json',
 'question_1868.json',
 'question_22840.json',
 'question_7378.json',
 'question_19118.json',
 'question_17427.json',
 'question_22931.json',
 'question_8124.json',
 'question_17816.json',
 'question_10267.json',
 'question_17755.json',
 'question_13040.json',
 'question_13708.json',
 'question_8698.json',
 'question_1319.json',
 'question_1308.json',
 'question_8942.json',
 'question_17152.json',
 'question_17318.json',
 'question_15881.json',
 'question_18535.json',
 'question_15759.json',
 'question_2172.json',
 'question_956.json',
 'question_4804.json',
 'question_5882.json',
 'question_11879.json',
 'question_8781.json',
 'question_23123.json',
 'question_17299.json',
 'question_11587.json',
 'question_526.json',
 'question_18320.json',
 'question_6056.json',
 'question_12127.json',
 'question_18131.json',
 'question_21220.json',
 'question_22996.json',
 'question_6640.json',
 'question_7773.json',
 'question_16007.json',
 'question_17296.json',
 'question_18767.json',
 'question_7404.json',
 'question_17310.json',
 'question_10100.json',
 'question_7102.json',
 'question_11295.json',
 'question_20891.json',
 'question_20306.json',
 'question_18576.json',
 'question_9763.json',
 'question_12299.json',
 'question_1719.json',
 'question_10518.json',
 'question_19799.json',
 'question_15238.json',
 'question_17598.json',
 'question_21221.json',
 'question_22392.json',
 'question_8894.json',
 'question_6884.json',
 'question_3579.json',
 'question_14305.json',
 'question_15116.json',
 'question_20382.json',
 'question_20753.json',
 'question_1944.json',
 'question_20127.json',
 'question_10668.json',
 'question_2600.json',
 'question_15011.json',
 'question_1305.json',
 'question_18524.json',
 'question_8500.json',
 'question_8868.json',
 'question_22901.json',
 'question_14958.json',
 'question_6478.json',
 'question_1731.json',
 'question_21058.json',
 'question_20245.json',
 'question_21599.json',
 'question_17975.json',
 'question_19146.json',
 'question_12347.json',
 'question_13244.json',
 'question_20191.json',
 'question_8376.json',
 'question_1949.json',
 'question_19565.json',
 'question_12713.json',
 'question_20283.json',
 'question_15806.json',
 'question_1038.json',
 'question_12757.json',
 'question_19116.json',
 'question_23350.json',
 'question_19377.json',
 'question_15792.json',
 'question_3916.json',
 'question_18357.json',
 'question_19098.json',
 'question_23552.json',
 'question_2407.json',
 'question_1369.json',
 'question_8024.json',
 'question_19422.json',
 'question_18704.json',
 'question_8314.json',
 'question_15509.json',
 'question_4785.json',
 'question_7294.json',
 'question_1316.json',
 'question_22409.json',
 'question_19630.json',
 'question_3417.json',
 'question_14887.json',
 'question_4970.json',
 'question_2603.json',
 'question_20730.json',
 'question_13176.json',
 'question_4743.json',
 'question_20264.json',
 'question_18266.json',
 'question_12847.json',
 'question_15709.json',
 'question_23243.json',
 'question_6670.json',
 'question_11248.json',
 'question_19314.json',
 'question_20710.json',
 'question_19769.json',
 'question_18206.json',
 'question_16721.json',
 'question_19623.json',
 'question_2492.json',
 'question_6975.json',
 'question_4280.json',
 'question_10400.json',
 'question_23011.json',
 'question_13603.json',
 'question_21936.json',
 'question_17558.json',
 'question_22951.json',
 'question_7741.json',
 'question_2.json',
 'question_8206.json',
 'question_23012.json',
 'question_14824.json',
 'question_780.json',
 'question_1441.json',
 'question_9599.json',
 'question_17826.json',
 'question_16722.json',
 'question_20002.json',
 'question_15576.json',
 'question_17541.json',
 'question_1283.json',
 'question_13483.json',
 'question_10695.json',
 'question_2650.json',
 'question_19227.json',
 'question_4826.json',
 'question_16868.json',
 'question_17071.json',
 'question_21601.json',
 'question_18910.json',
 'question_18425.json',
 'question_4806.json',
 'question_7395.json',
 'question_21082.json',
 'question_19557.json',
 'question_18306.json',
 'question_22589.json',
 'question_3957.json',
 'question_19228.json',
 'question_18294.json',
 'question_12084.json',
 'question_14140.json',
 'question_16712.json',
 'question_3326.json',
 'question_23458.json',
 'question_2264.json',
 'question_7364.json',
 'question_15741.json',
 'question_18676.json',
 'question_14127.json',
 'question_22955.json',
 'question_20842.json',
 'question_19900.json',
 'question_21610.json',
 'question_6578.json',
 'question_2303.json',
 'question_3606.json',
 'question_9647.json',
 'question_17937.json',
 'question_22063.json',
 'question_14153.json',
 'question_15758.json',
 'question_17208.json',
 'question_19134.json',
 'question_14181.json',
 'question_9056.json',
 'question_20620.json',
 'question_18996.json',
 'question_8039.json',
 'question_5993.json',
 'question_18246.json',
 'question_14501.json',
 'question_8005.json',
 'question_21234.json',
 'question_7189.json',
 'question_21714.json',
 'question_7945.json',
 'question_23403.json',
 'question_12617.json',
 'question_11547.json',
 'question_13979.json',
 'question_16737.json',
 'question_8736.json',
 'question_14735.json',
 'question_11593.json',
 'question_13241.json',
 'question_3904.json',
 'question_13172.json',
 'question_1290.json',
 'question_8343.json',
 'question_19729.json',
 'question_10697.json',
 'question_13326.json',
 'question_3127.json',
 'question_11266.json',
 'question_8064.json',
 'question_15827.json',
 'question_17500.json',
 'question_2730.json',
 'question_2426.json',
 'question_3728.json',
 'question_3935.json',
 'question_13319.json',
 'question_17947.json',
 'question_6536.json',
 'question_11891.json',
 'question_6885.json',
 'question_6228.json',
 'question_20446.json',
 'question_16775.json',
 'question_16281.json',
 'question_9946.json',
 'question_23682.json',
 'question_20025.json',
 'question_2972.json',
 'question_18261.json',
 'question_12134.json',
 'question_19171.json',
 'question_22304.json',
 'question_5277.json',
 'question_14451.json',
 'question_4805.json',
 'question_16689.json',
 'question_4999.json',
 'question_19084.json',
 'question_9869.json',
 'question_20007.json',
 'question_17879.json',
 'question_3639.json',
 'question_13548.json',
 'question_13366.json',
 'question_6651.json',
 'question_21252.json',
 'question_2946.json',
 'question_2280.json',
 'question_13864.json',
 'question_3394.json',
 'question_11376.json',
 'question_9644.json',
 'question_18030.json',
 'question_13829.json',
 'question_6894.json',
 'question_9843.json',
 'question_11505.json',
 'question_5883.json',
 'question_9548.json',
 'question_3878.json',
 'question_21834.json',
 'question_12332.json',
 'question_1822.json',
 'question_3225.json',
 'question_21790.json',
 'question_8822.json',
 'question_12580.json',
 'question_13828.json',
 'question_13230.json',
 'question_2478.json',
 'question_8580.json',
 'question_20581.json',
 'question_15835.json',
 'question_18868.json',
 'question_22547.json',
 'question_16104.json',
 'question_8489.json',
 'question_14040.json',
 'question_14830.json',
 'question_10148.json',
 'question_7430.json',
 'question_5231.json',
 'question_21442.json',
 'question_13981.json',
 'question_19161.json',
 'question_21199.json',
 'question_10013.json',
 'question_5388.json',
 'question_21027.json',
 'question_1544.json',
 'question_9259.json',
 'question_20908.json',
 'question_7228.json',
 'question_4691.json',
 'question_21775.json',
 'question_15416.json',
 'question_15191.json',
 'question_1966.json',
 'question_17686.json',
 'question_18440.json',
 'question_11910.json',
 'question_23017.json',
 'question_16032.json',
 'question_22828.json',
 'question_2487.json',
 'question_17599.json',
 'question_7496.json',
 'question_9918.json',
 'question_18157.json',
 'question_16747.json',
 'question_1475.json',
 'question_6897.json',
 'question_9086.json',
 'question_15060.json',
 'question_11535.json',
 'question_4242.json',
 'question_23651.json',
 'question_2170.json',
 'question_6532.json',
 'question_9078.json',
 'question_19082.json',
 'question_22244.json',
 'question_13958.json',
 'question_18916.json',
 'question_15658.json',
 'question_20829.json',
 'question_18238.json',
 'question_16678.json',
 'question_11236.json',
 'question_7757.json',
 'question_8164.json',
 'question_19716.json',
 'question_2136.json',
 'question_3278.json',
 'question_20346.json',
 'question_5431.json',
 'question_19713.json',
 'question_1504.json',
 'question_20202.json',
 'question_3962.json',
 'question_8203.json',
 'question_21629.json',
 'question_12089.json',
 'question_20705.json',
 'question_570.json',
 'question_8304.json',
 'question_16543.json',
 'question_10399.json',
 'question_5531.json',
 'question_23311.json',
 'question_7790.json',
 'question_1049.json',
 'question_23329.json',
 'question_10322.json',
 'question_23512.json',
 'question_18864.json',
 'question_22973.json',
 'question_16322.json',
 'question_15670.json',
 'question_16884.json',
 'question_12055.json',
 'question_15677.json',
 'question_20352.json',
 'question_11048.json',
 'question_18628.json',
 'question_19333.json',
 'question_4971.json',
 'question_18616.json',
 'question_21486.json',
 'question_8845.json',
 'question_21335.json',
 'question_16729.json',
 'question_20353.json',
 'question_9512.json',
 'question_1853.json',
 'question_22655.json',
 'question_502.json',
 'question_2988.json',
 'question_11774.json',
 'question_19334.json',
 'question_855.json',
 'question_10962.json',
 'question_20319.json',
 'question_9634.json',
 'question_9028.json',
 'question_12679.json',
 'question_19135.json',
 'question_14068.json',
 'question_20001.json',
 'question_13424.json',
 'question_5809.json',
 'question_521.json',
 'question_5041.json',
 'question_11886.json',
 'question_13000.json',
 'question_14736.json',
 'question_18723.json',
 'question_18860.json',
 'question_23088.json',
 'question_21015.json',
 'question_19707.json',
 'question_16487.json',
 'question_22915.json',
 'question_5000.json',
 'question_15970.json',
 'question_19734.json',
 'question_7648.json',
 'question_9926.json',
 'question_19250.json',
 'question_20568.json',
 'question_22851.json',
 'question_444.json',
 'question_18694.json',
 'question_17407.json',
 'question_20277.json',
 'question_268.json',
 'question_23237.json',
 'question_19929.json',
 'question_7752.json',
 'question_17657.json',
 'question_22142.json',
 'question_4561.json',
 'question_11081.json',
 'question_5876.json',
 'question_4718.json',
 'question_1627.json',
 'question_251.json',
 'question_22683.json',
 'question_732.json',
 'question_14829.json',
 'question_12610.json',
 'question_969.json',
 'question_21359.json',
 'question_23152.json',
 'question_18088.json',
 'question_19531.json',
 'question_7315.json',
 'question_3781.json',
 'question_18096.json',
 'question_21431.json',
 'question_11186.json',
 'question_14935.json',
 'question_4407.json',
 'question_17089.json',
 'question_19944.json',
 'question_16117.json',
 'question_13115.json',
 'question_10767.json',
 'question_21279.json',
 'question_23157.json',
 'question_16471.json',
 'question_14138.json',
 'question_874.json',
 'question_2325.json',
 'question_697.json',
 'question_15656.json',
 'question_6307.json',

In [5]:
dataset = pk.load(open("tree_dataset.pkl", "rb"))

In [6]:
dataset

,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality
question_3158.json,Did Cristiano dos Santos Rodrigues play in mor...,76,Sports,season (which had more games played),comparison result,"[table, table]"
question_13163.json,Which of the home media of ICarly : the Comple...,99,Television,home media release (which one has higher disc ...,media release,"[table, table]"
question_10777.json,"Was It's Like, You Know... or Friends, the one...",106,Television,television series title (one of two options),work,"[table, table]"
question_6283.json,The Usher song Yeah! charted lower in which Ch...,119,Music,chart (music chart name/market),chart,"[table, table]"
question_17285.json,In the chart performance from 1983 for the son...,152,Music,chart name (which had the lower peak position),string,"[table, table]"
...,...,...,...,...,...,...
question_23543.json,"Which Location(s), in Teams and locations of 1...",112,Sports,location(s) (place names listed in 'Teams and ...,location,[image]
question_15516.json,What color jacket is Hammer & Tongs wearing?,44,Other,color (jacket color),attribute,[image]
question_189.json,What color teeth does Goldie have?,34,Other,color (teeth color),attribute,[image]
question_14280.json,"Is the red stripe on the left, center, or righ...",76,Geography,relative position (left/center/right),attribute,[image]
question_3707.json,What pattern are the men in Crossout wearing?,45,Video games,clothing pattern,attribute,[image]

In [178]:
def dataset_build(dataset):
    image_rows = dataset[dataset["modality"].astype(str) == "['image']"].sample(20, random_state=42)
    text_rows  = dataset[dataset["modality"].astype(str) == "['text']"].sample(20, random_state=42)
    table_rows = dataset[dataset["modality"].astype(str) == "['table']"].sample(20, random_state=42)
    
    test_dataset = pd.concat([image_rows, text_rows, table_rows]) \
                   .sample(frac=1, random_state=42) \
                   .reset_index(drop=False)
    
    return test_dataset

In [179]:
test_dataset = dataset_build(dataset)

In [180]:
test_dataset["modality_answers"] = [[] for _ in range(len(test_dataset))]

In [181]:
test_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_13547.json,What object is seen in the center of the Days ...,66,Television,object depicted (center of poster),object,[image],[]
1,question_14691.json,How many people are wearing a black and red st...,92,Sports,count of people,number,[image],[]
2,question_5497.json,The Red Bull RB8 is a Formula One racing car d...,240,Sports,racing team / organization,organization,[text],[]
3,question_11881.json,"was Tha Eastsidaz the Featuring, in track list...",106,Music,yes/no (whether an artist is a featured act on...,boolean,[table],[]
4,question_10110.json,What general pattern is on Lionel Messi's jersey?,49,Sports,jersey pattern (description),attribute,[image],[]
5,question_5821.json,Was the 2005-06 AHL season in Scott Gordon's m...,96,Sports,yes/no (boolean),boolean,[table],[]
6,question_10556.json,who plays nina's mom on general hospital,40,Television,actor/actress (cast member),person,[text],[]
7,question_11778.json,Who was the operator when the route was N30 in...,72,Transportation,operator (organization/company),organization,[table],[]
8,question_11017.json,What color is the car parked up against the cu...,119,Other,color,attribute,[image],[]
9,question_10128.json,In what year was Lauren Crace in the film Silk?,47,Film,year,time,[table],[]
10,question_21696.json,"In the 2009 FC Rostov season transfers in, wha...",117,Sports,football (soccer) club name,organization,[table],[]
11,question_6981.json,In what seasons did Karlee Burgess compete in ...,115,Sports,seasons (years or season ranges) of competition,time period,[table],[]
12,question_17896.json,who sings paint it black in the last witch hunter,49,Film,singer/performing artist (person or band),person or organization,[text],[]
13,question_1705.json,What main color besides purple makes up the un...,90,Sports,color (uniform component),attribute,[image],[]
14,question_4652.json,What was the highest points total during the 1...,100,Sports,highest points total (number of points) by a p...,number,[table],[]
15,question_5385.json,"Which Location(s), in Current members of Commo...",119,Geography,location (place name),geographic entity,[image],[]
16,question_23543.json,"Which Location(s), in Teams and locations of 1...",112,Sports,location(s) (place names listed in 'Teams and ...,location,[image],[]
17,question_1820.json,What color are the tree leaves in this photo o...,63,Geography,color (tree leaf color in the photo),attribute/value,[image],[]
18,question_23720.json,Was Toni Polster the Austrian Football Bundesl...,83,Sports,yes/no (boolean),boolean,[table],[]
19,question_17634.json,Which location with red seating areas is where...,82,Sports,location (venue/stadium/track) with red seatin...,location,[image],[]
20,question_18327.json,What team did Fred Durrant play on during the ...,61,Sports,team name,sports team,[table],[]
21,question_21962.json,A company with a seashell on its logo sponsore...,98,Sports,racing driver(s),person,[image],[]
22,question_18132.json,Which of the three geological formations expos...,149,Geography,geological formation name,geological formation,[text],[]
23,question_5731.json,What is the first year that Dragons de Rouen w...,73,Sports,year,time,[table],[]
24,question_15730.json,who won the world best player of the year 2018,46,Sports,person (winner of an award),person,[text],[]
25,question_9007.json,Stig Blomqvist had Bjorn Cederberg as his co-d...,115,Sports,year of event,time,[table],[]
26,question_9903.json,What animal is standing behind Lakshmana?,41,Other,animal species/type,animal,[image],[]
27,question_16691.json,stars in 10 things i hate about you,35,Film,actor/actress (cast member),person,[text],[]
28,question_18986.json,"Which Driver(s), in Past winners of Henry 180,...",72,Sports,driver name(s),person,[image],[]
29,question_10541.json,when does the us open air on tv,31,Sports,TV broadcast time (date/time schedule),time,[text],[]
30,question_18965.json,when was the first year athletic trainers orga...,69,Sports,year,date/time,[text],[]
31,question_17656.json,Which player with a long beard and mustache fr...,106,Sports,football player,person,[image],[]
32,question_21958.json,In which city was the band whose members wrote...,71,Music,city,location,[text],[]
33,question_19112.json,During the 2011-12 season in Career statistics...,129,Sports,yes/no answer,boolean,[table],[]
34,question_14280.json,"Is the red stripe on the left, center, or righ...",76,Geography,relative position (left/center/right),attribute,[image],[]
35,question_5853.json,Eric McCormack from the TV series Perception a...,98,Television,science fiction television series,television series,[text],[]
36,question_1175.json,"In season 2 of the Tapout TV series, who were ...",96,Television,fighters (people) featured in a TV episode,person,[table],[]
37,question_20383.json,"was Tamil Nadu the State, in new lines of Sout...",99,Transportation,yes/no determination,boolean,[table],[]
38,question_8638.json,who played harper on wizards of waverly place,45,Television,actor,person,[text],[]
39,question_1160.json,How many Tony Awards have been received by the...,117,Theater,number of Tony Awards received,number,[text],[]
40,question_6804.json,"What was the singers of ""Mera Yaar Dildaar"" in...",68,Film,singer(s) of a film song,person,[table],[]
41,question_11373.json,Among the Argentine football teams that were r...,125,Sports,Argentine football team (club) name,sports team,[image],[]
42,question_2960.json,when does tom clancy's the division come out,44,Video games,release date,date,[text],[]
43,question_16127.json,What are the players wearing around their neck...,101,Sports,item worn around the neck,object,[image],[]
44,question_7962.json,What was the name of the film in which Torri H...,80,Film,film title,creative work,[table],[]
45,question_23452.json,In what state is Alice Lioyd College and June ...,62,Geography,U.S. state,location,[text],[]
46,question_3615.json,The 2012–13 FC Bayern Munich season was the 11...,436,Sports,name of a German top-flight football league,sports league,[text],[]
47,question_10324.json,what was the first year of the nissan gtr,41,Transportation,first production/model year (year),year,[text],[]
48,question_6120.json,What was the result of the Army of Conquest Al...,86,History,battle outcome/result,outcome,[table],[]
49,question_17242.json,What celestial body is on the horizon on the l...,72,Television,celestial body (object shown in logo),astronomical object,[image],[]
50,question_11053.json,What English actor appeared in films like “The...,155,Film,English actor,person,[text],[]
51,question_6230.json,"Which Series(s), in Television of Dave Grohl, ...",102,Television,television series title,television series,[image],[]
52,question_12631.json,What team had a PCT of 0.611 during the regula...,72,Sports,team,organization,[table],[]
53,question_21492.json,where is the most wine produced in the us,41,Geography,U.S. state or region (place) with highest wine...,Location,[text],[]
54,question_10979.json,What does the person have around his hands in ...,78,Film,object around hands,object,[image],[]
55,question_8285.json,What albums did Paul Williams release on the A...,63,Music,album titles,creative works,[table],[]
56,question_11613.json,What is the main color in this aerial view of ...,54,Geography,color,attribute,[image],[]
57,question_4497.json,Doctor Maya Lahan is a fictional character fro...,221,Television,television series (title),creative work,[text],[]
58,question_3674.json,"During the season of 2019-20, how many goals d...",67,Sports,number of goals,number,[table],[]
59,question_5929.json,who did the patriots beat in the last super bowl,48,Sports,opponent team (Super Bowl),sports team,[text],[]

In [41]:
class ModalityResponse(BaseModel):
    answer: Literal["YES", "NO"] = Field(..., description="Whether the question can be answered using ONLY the given data element and its metadata")

In [14]:
def encode_image(image_path):
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

In [15]:
client = OpenAI(api_key=OPENAI_KEY)

# First Approach: It also tells which specific piece of data contains the answer

In [95]:
def prompt_image(question, image): 
    image64 = encode_image(os.path.join(FINAL_DATASET_IMAGES, image["path"]))
    
    print("Question: ", question)
    print("Image title: ", image["title"])
    print("Image path: ", image["path"])

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.
                            
                You will be given:
                - A question
                - ONE image
                - The title of the image
                
                Your job is to decide whether the question can be answered using ONLY this single image and its title.
                
                Rules:
                - Use only the provided data item. Do not use outside knowledge or your knowledge.
                - Do not assume other images exist.
                - Do not guess.
                - If the answer is not directly visible or inferable from the image/title, respond NO.
                - If the image/title contains enough information to confidently answer, respond YES.
                
                Output MUST be exactly one word: YES or NO.
                """
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": f"""Question: {question}
                        Title: {image["title"]}

                        Can the question be answered using ONLY this image and its title?
                        """
                    },
                    {
                        "type": "input_image",
                        "image_url": f"data:image/jpeg;base64,{image64}"
                    },
                ]
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    print(answer)
    return answer

In [96]:
def prompt_text(question, text):
    
    print("Question: ", question)
    print("Title: ", text["title"])
    print("Text: ", text["text"])

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.
                            
                You will be given:
                - A question
                - ONE paragraph (text content)
                - The title of the paragraph
                
                Your job is to decide whether the question can be answered using ONLY this single paragraph and its title.
                
                Rules:
                - Use only the provided paragraph and title. Do not use outside knowledge or your own knoweldge.
                - Do not assume other paragraphs exist.
                - Do not guess.
                - If the answer is not explicitly stated or clearly derivable from the paragraph/title, respond NO.
                - If the paragraph/title contains enough information to confidently answer, respond YES.
                
                Output MUST be exactly one word: YES or NO.
                """
            },
            {
                "role": "user",
                "content": f"""Question: {question}
                
                Title: {text["title"]}
                
                Paragraph Content: {text["text"]}

                Can the question be answered using ONLY this paragraph and its title?
                """
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    print(answer)
    return answer

In [136]:
def prompt_table(question, table):
    
    json_table = json.load(open(os.path.join(TABLE_DIR, table["json"]), "rb"))
    
    print("Question: ", question)
    print("Title: ", json_table["title"])
    print("Table: ", json_table["table"])

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.

                You will be given:
                - A question
                - ONE table (structured data)
                - The title of the table
                
                Your job is to decide whether the question can be answered using ONLY this single table and its title.
                
                Rules:
                - Use only the provided table and title. Do not use outside knowledge or your knowledge.
                - Do not assume other tables exist.
                - Do not guess.
                - If the answer is not explicitly present or cannot be derived from the table, respond NO.
                - If the table contains enough information to confidently answer, respond YES.
                
                Output MUST be exactly one word: YES or NO.
                """
            },
            {
                "role": "user",
                "content": f"""Question: {question["original_question"]}
                
                Title: {json_table["title"]}
                
                Table Content: {json_table["table"]}
                
                Can the question be answered using ONLY this table and its title?
                """
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    print(answer)
    return answer

In [98]:
def gather_answers(question, modality, set): 
    answers, yes_dict = [], {"YES": []}
    if modality == "image": 
        for data_sample in set: 
            answer = prompt_image(question["original_question"], data_sample)
            answers.append(answer)
            if answer == "YES": yes_dict["YES"].append(question["index"])
    elif modality == "text": 
        for data_sample in set: 
            answer = prompt_text(question["original_question"], data_sample)
            answers.append(answer)
            if answer == "YES": yes_dict["YES"].append(question["index"])
    elif modality == "table": 
        for data_sample in set: 
            answer = prompt_table(question["original_question"], data_sample)
            answers.append(answer)
            if answer == "YES": yes_dict["YES"].append(question["index"])
            
    return answers

In [99]:
def check_modality(answers, modality):
    if any(answer=="YES" for answer in answers): 
        return modality

In [100]:
for i, question in test_dataset.iterrows(): 
    print(f"Question: {i}, {question['index']}")
    json_association = json.load(open(os.path.join(ASSOCIATION_DIR, question["index"]), "rb"))
    
    image_set = json_association["image_set"][:2]
    text_set = json_association["text_set"][:2]
    table_set = json_association["table_set"][:1]
    
    # Gather answers for image
    answers_image = gather_answers(question, "image", image_set)
    print("The answers for the images are: ", answers_image)
    check_modality(answers_image, "image")
    
    # Gather answers for text
    answers_text = gather_answers(question, "text", text_set)
    check_modality(answers_text, "text")
    
    # Gather answers for table
    answers_table = gather_answers(question, "table", table_set)
    check_modality(answers_table, "table")
    
    break

Question: 0, question_13547.json
Question:  What object is seen in the center of the Days of Our Lives poster?
Image title:  Days of Our Lives
Image path:  02e80d4acbc03c25592eeae21054713d.jpg
YES
Question:  What object is seen in the center of the Days of Our Lives poster?
Image title:  Kickin' It
Image path:  592fac145be775ffcb94cd4a6a69cd0f.png
NO
The answers for the images are:  ['YES', 'NO']
Question:  What object is seen in the center of the Days of Our Lives poster?
Title:  Boy Scout Memorial
Text:  The sculpture consists of three bronze figures: a Boy Scout in the center wearing a uniform stepping forward and carrying a walking stick in his left hand. Flanking him are two larger allegorical figures of a man and woman. They represent "American Manhood and Womanhood and the ideals they will pass onto the youth." To the Boy Scout's right side is the male figure, nearly nude, who carries a bundle of leaves and drapery in his left arm. Part of the drapery blows across his middle as he strides forward with his right leg. To the Scout's left side is the female figure who holds a torch in her left hand that has a gold-colored flame. Her left hand extends slightly and her palm is facing upward and she strides forward on her right leg. The three figures are mounted on a hexagonal-shaped base (62 x 92 x 98 in.) and in front of the sculpture is a circular pool of water.
NO
Question:  What object is seen in the center of the Days of Our Lives poster?
Title:  Skipping Girl Sign
Text:  The sign consists of a painted metal structure outlined in neon tubing depicting a little girl skipping rope. At night the sign's outlines are illuminated, the skipping rope being displayed in four sequential positions to give the appearance of motion.
NO
Question:  What object is seen in the center of the Days of Our Lives poster?
Title:  Donald Li
Table:  {'table_rows': [[{'text': '1985', 'links': []}, {'text': 'The Equalizer', 'links': [{'text': 'The Equalizer', 'wiki_title': 'The Equalizer (TV series)', 'url': 'https://en.wikipedia.org/wiki/The_Equalizer_(TV_series)'}]}, {'text': 'Joe Boy', 'links': []}, {'text': 'Episode: "China Rain"', 'links': []}], [{'text': '1989', 'links': []}, {'text': 'Gideon Oliver', 'links': [{'text': 'Gideon Oliver', 'wiki_title': 'Gideon Oliver', 'url': 'https://en.wikipedia.org/wiki/Gideon_Oliver'}]}, {'text': '', 'links': []}, {'text': 'Episode: "Tongs"', 'links': []}], [{'text': '1992', 'links': []}, {'text': 'Bodies of Evidence', 'links': [{'text': 'Bodies of Evidence', 'wiki_title': 'Bodies of Evidence (TV series)', 'url': 'https://en.wikipedia.org/wiki/Bodies_of_Evidence_(TV_series)'}]}, {'text': 'Charlie Yung', 'links': []}, {'text': 'Episode: "Nightmoves"', 'links': []}], [{'text': '1992', 'links': []}, {'text': 'Knots Landing', 'links': [{'text': 'Knots Landing', 'wiki_title': 'Knots Landing', 'url': 'https://en.wikipedia.org/wiki/Knots_Landing'}]}, {'text': 'Bailiff', 'links': []}, {'text': 'Episode: "Rescue Me"', 'links': []}], [{'text': '1997', 'links': []}, {'text': 'Nash Bridges', 'links': [{'text': 'Nash Bridges', 'wiki_title': 'Nash Bridges', 'url': 'https://en.wikipedia.org/wiki/Nash_Bridges'}]}, {'text': 'Elliot Lim', 'links': []}, {'text': 'Episode: "The Web"', 'links': []}], [{'text': '2001', 'links': []}, {'text': 'The Practice', 'links': [{'text': 'The Practice', 'wiki_title': 'The Practice', 'url': 'https://en.wikipedia.org/wiki/The_Practice'}]}, {'text': 'Juror', 'links': []}, {'text': 'Episode: "Gideons Crossover" (uncredited)', 'links': []}], [{'text': '2009', 'links': []}, {'text': 'Numbers', 'links': [{'text': 'Numbers', 'wiki_title': 'Numbers (TV series)', 'url': 'https://en.wikipedia.org/wiki/Numbers_(TV_series)'}]}, {'text': 'Waiter #1', 'links': []}, {'text': 'Episode: "Trouble in Chinatown"', 'links': []}], [{'text': '2009', 'links': []}, {'text': 'The Bold and the Beautiful', 'links': [{'text': 'The Bold and the Beautiful', 'wiki_title': 'The Bold and the Beautiful', 'url': 'https://en.wikipedia.org/wiki/The_Bold_and_the_Beautiful'}]}, {'text': 'Minister', 'links': []}, {'text': 'Episode: "#1.5575" (uncredited)', 'links': []}], [{'text': '2009-2010', 'links': []}, {'text': 'Better Off Ted', 'links': [{'text': 'Better Off Ted', 'wiki_title': 'Better Off Ted', 'url': 'https://en.wikipedia.org/wiki/Better_Off_Ted'}]}, {'text': 'Office Worker / Asian Man', 'links': []}, {'text': 'Episodes: "Win Some, Dose Some" (uncredited), "Swag the Dog"', 'links': []}], [{'text': '2010', 'links': []}, {'text': 'Southland', 'links': [{'text': 'Southland', 'wiki_title': 'Southland (TV series)', 'url': 'https://en.wikipedia.org/wiki/Southland_(TV_series)'}]}, {'text': 'Coroner', 'links': []}, {'text': 'Episode: "The Runner"', 'links': []}], [{'text': '2010', 'links': []}, {'text': 'Romantically Challenged', 'links': [{'text': 'Romantically Challenged', 'wiki_title': 'Romantically Challenged', 'url': 'https://en.wikipedia.org/wiki/Romantically_Challenged'}]}, {'text': 'Owner', 'links': []}, {'text': 'Episode: "Rebeccas One Night Stand"', 'links': []}], [{'text': '2012', 'links': []}, {'text': "Kickin' It", 'links': [{'text': "Kickin' It", 'wiki_title': "Kickin' It", 'url': "https://en.wikipedia.org/wiki/Kickin'_It"}]}, {'text': 'Doctor Chen', 'links': []}, {'text': 'Episode: "Kickin It in China"', 'links': []}], [{'text': '2014', 'links': []}, {'text': 'Days of Our Lives', 'links': [{'text': 'Days of Our Lives', 'wiki_title': 'Days of Our Lives', 'url': 'https://en.wikipedia.org/wiki/Days_of_Our_Lives'}]}, {'text': 'Mr. Shinn', 'links': []}, {'text': 'Episodes: "#1.12374", "#1.12375"', 'links': []}], [{'text': '2015', 'links': []}, {'text': 'Shameless', 'links': [{'text': 'Shameless', 'wiki_title': 'Shameless (U.S. TV series)', 'url': 'https://en.wikipedia.org/wiki/Shameless_(U.S._TV_series)'}]}, {'text': 'Maitre D', 'links': []}, {'text': 'Episode: "A Night to Remem-- Wait, What?"', 'links': []}], [{'text': '2015-2016', 'links': []}, {'text': 'Bosch', 'links': [{'text': 'Bosch', 'wiki_title': 'Bosch (TV series)', 'url': 'https://en.wikipedia.org/wiki/Bosch_(TV_series)'}]}, {'text': 'Charlie Lui', 'links': []}, {'text': 'Episodes: "Victim of the Night", "Chapter Six: Donkeys Years"', 'links': []}], [{'text': '2016', 'links': []}, {'text': 'Idiotsitter', 'links': [{'text': 'Idiotsitter', 'wiki_title': 'Idiotsitter', 'url': 'https://en.wikipedia.org/wiki/Idiotsitter'}]}, {'text': 'Mr. Sasaki', 'links': []}, {'text': 'Episodes: "Viva La Joy", "Funeral"', 'links': []}], [{'text': '2017', 'links': []}, {'text': 'Hand of God', 'links': [{'text': 'Hand of God', 'wiki_title': 'Hand of God (TV series)', 'url': 'https://en.wikipedia.org/wiki/Hand_of_God_(TV_series)'}]}, {'text': 'Reporter #2', 'links': []}, {'text': 'Episode: "You Cant Go Back"', 'links': []}]], 'table_name': 'Television series', 'header': [{'column_name': 'Year', 'metadata': {'num_of_links': 0, 'ner_appearances_map': {'DATE': 15, 'CARDINAL': 2}}}, {'column_name': 'Title', 'metadata': {'num_of_links': 17, 'ner_appearances_map': {'ORG': 1, 'PERSON': 1}, 'is_key_column': True, 'image_associated_column': True, 'entities_column': True}}, {'column_name': 'Role', 'metadata': {'num_of_links': 0, 'ner_appearances_map': {'PERSON': 8, 'CARDINAL': 2, 'NORP': 1}}}, {'column_name': 'Notes', 'metadata': {'num_of_links': 0, 'ner_appearances_map': {'WORK_OF_ART': 10, 'MONEY': 1}}}]}
NO

# Second Approach: Here we now do that we give all the images at ones, all the paragraphs at ones

In [195]:
class ModalityResponse(BaseModel):
    answer: Literal["YES", "NO"] = Field(..., description="Whether the question can be answered using ONLY the given data elements and their metadata")

In [196]:
def prompt_images(question, images):
    # Encode all images
    image_inputs = []
    for img in images:
        image64 = encode_image(os.path.join(FINAL_DATASET_IMAGES, img["path"]))
        image_inputs.append({
            "title": img["title"],
            "image_url": f"data:image/jpeg;base64,{image64}"
        })
    
    # Prepare textual description of all images
    images_text = "\n".join([f"{i+1}. Title: {img['title']}" for i, img in enumerate(images)])

    #print("Question: ", question["original_question"])
    #print("Images provided:")
    for img in images:
        print("-", img["title"], img["path"])
        
    #print("Images texts: ", images_text)
    
    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.

                You will be given:
                - A question
                - A list of images with their titles
                
                Your job is to decide whether the question can be answered using ONLY the information in these images and their titles.
                
                Rules:
                - Use only the provided images and titles. Do not use outside knowledge or your knowledge.
                - Do not guess.
                - If the answer is derivable from at least one image/title, respond YES.
                - If none of the images contain enough information, respond NO.
                
                Output MUST be exactly one word: YES or NO.
                """
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": f"""Question: {question["original_question"]}
                        
                        Images: {images_text}
                        
                        Can the question be answered using ONLY these images and their titles?
                        """
                    },
                    
                    # attach all images
                    *[
                        {"type": "input_image", "image_url": img["image_url"]} for img in image_inputs
                    ]
                ]
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    return answer

In [225]:
def prompt_texts(question, paragraphs):
    
    # Prepare textual representation for all paragraphs
    paragraphs_text = "\n\n".join([
        f"{i+1}. Title: {p['title']}\nContent: {p['text']}" 
        for i, p in enumerate(paragraphs)
    ])
    
    #print("Question:", question["original_question"])
    #print("Paragraphs provided:")
    for p in paragraphs:
        print("-", p["title"])
        
    print("Paragraphs texts: ", paragraphs_text)
    
    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.

                            You will be given:
                            - A question
                            - A list of paragraphs with their titles
                            
                            Your job is to decide whether the question can be answered using ONLY the information in these paragraphs and their titles.
                            
                            Rules:
                            - Use only the provided paragraphs and titles. Do not use outside knowledge.
                            - Do not guess.
                            - If the answer can be derived from at least one paragraph/title, respond YES.
                            - If none of the paragraphs contain enough information, respond NO.
                            
                            Output MUST be exactly one word: YES or NO.
                            """
            },
            {
                "role": "user",
                "content": f"""Question: {question["original_question"]}
                
                Paragraphs: {paragraphs_text}
                
                Can the question be answered using ONLY at least one these paragraphs and their titles?
                """
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    return answer

In [198]:
def prompt_table(question, table):
    
    json_table = json.load(open(os.path.join(TABLE_DIR, table["json"]), "rb"))
    
    #print("Question: ", question["original_question"])
    #print("Title: ", json_table["title"])
    #print("Table: ", json_table["table"])

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """You are a modality suitability judge.

                You will be given:
                - A question
                - ONE table (structured data)
                - The title of the table
                
                Your job is to decide whether the question can be answered using ONLY this single table and its title.
                
                Rules:
                - Use only the provided table and title. Do not use outside knowledge or your knowledge.
                - Do not assume other tables exist.
                - Do not guess.
                - If the answer is not explicitly present or cannot be derived from the table, respond NO.
                - If the table contains enough information to confidently answer, respond YES.
                
                Output MUST be exactly one word: YES or NO.
                """
            },
            {
                "role": "user",
                "content": f"""Question: {question["original_question"]}
                
                Title: {json_table["title"]}
                
                Table Content: {json_table["table"]}
                
                Can the question be answered using ONLY this table and its title?
                """
            }
        ],
        text_format=ModalityResponse,
    )
    
    answer = response.output_parsed.answer
    return answer

In [256]:
def derive_answers(dataset): 
    for i, question in dataset.iterrows(): 
        print(f"Question number: {i}, Question JSON: {question['index']}, Question: {question['original_question']}")
        json_association = json.load(open(os.path.join(ASSOCIATION_DIR, question["index"]), "rb"))
        
        image_set = json_association["image_set"]
        text_set = json_association["text_set"]
        table_set = json_association["table_set"][0]
        
        answer_images = prompt_images(question, image_set)
        answer_texts = prompt_texts(question, text_set)
        answer_table = prompt_table(question, table_set)
        
        print("Answer for images: ", answer_images)
        print("Answer for text: ", answer_texts)
        print("Answer for table: ", answer_table)
        
        modality_answers = []
        
        if answer_images == "YES":
            modality_answers.append("image")
            
        if answer_texts == "YES": 
            modality_answers.append("text")
            
        if answer_table == "YES": 
            modality_answers.append("table")
        
        dataset.at[i, "modality_answers"] = modality_answers

In [232]:
test_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_13547.json,What object is seen in the center of the Days ...,66,Television,object depicted (center of poster),object,[image],[image]
1,question_14691.json,How many people are wearing a black and red st...,92,Sports,count of people,number,[image],[image]
2,question_5497.json,The Red Bull RB8 is a Formula One racing car d...,240,Sports,racing team / organization,organization,[text],[text]
3,question_11881.json,"was Tha Eastsidaz the Featuring, in track list...",106,Music,yes/no (whether an artist is a featured act on...,boolean,[table],[]
4,question_10110.json,What general pattern is on Lionel Messi's jersey?,49,Sports,jersey pattern (description),attribute,[image],[image]
5,question_5821.json,Was the 2005-06 AHL season in Scott Gordon's m...,96,Sports,yes/no (boolean),boolean,[table],[]
6,question_10556.json,who plays nina's mom on general hospital,40,Television,actor/actress (cast member),person,[text],[text]
7,question_11778.json,Who was the operator when the route was N30 in...,72,Transportation,operator (organization/company),organization,[table],[table]
8,question_11017.json,What color is the car parked up against the cu...,119,Other,color,attribute,[image],[image]
9,question_10128.json,In what year was Lauren Crace in the film Silk?,47,Film,year,time,[table],[table]
10,question_21696.json,"In the 2009 FC Rostov season transfers in, wha...",117,Sports,football (soccer) club name,organization,[table],[table]
11,question_6981.json,In what seasons did Karlee Burgess compete in ...,115,Sports,seasons (years or season ranges) of competition,time period,[table],[table]
12,question_17896.json,who sings paint it black in the last witch hunter,49,Film,singer/performing artist (person or band),person or organization,[text],[text]
13,question_1705.json,What main color besides purple makes up the un...,90,Sports,color (uniform component),attribute,[image],[image]
14,question_4652.json,What was the highest points total during the 1...,100,Sports,highest points total (number of points) by a p...,number,[table],[table]
15,question_5385.json,"Which Location(s), in Current members of Commo...",119,Geography,location (place name),geographic entity,[image],[image]
16,question_23543.json,"Which Location(s), in Teams and locations of 1...",112,Sports,location(s) (place names listed in 'Teams and ...,location,[image],[image]
17,question_1820.json,What color are the tree leaves in this photo o...,63,Geography,color (tree leaf color in the photo),attribute/value,[image],[image]
18,question_23720.json,Was Toni Polster the Austrian Football Bundesl...,83,Sports,yes/no (boolean),boolean,[table],[table]
19,question_17634.json,Which location with red seating areas is where...,82,Sports,location (venue/stadium/track) with red seatin...,location,[image],[]
20,question_18327.json,What team did Fred Durrant play on during the ...,61,Sports,team name,sports team,[table],[table]
21,question_21962.json,A company with a seashell on its logo sponsore...,98,Sports,racing driver(s),person,[image],[image]
22,question_18132.json,Which of the three geological formations expos...,149,Geography,geological formation name,geological formation,[text],[text]
23,question_5731.json,What is the first year that Dragons de Rouen w...,73,Sports,year,time,[table],[table]
24,question_15730.json,who won the world best player of the year 2018,46,Sports,person (winner of an award),person,[text],[text]
25,question_9007.json,Stig Blomqvist had Bjorn Cederberg as his co-d...,115,Sports,year of event,time,[table],[table]
26,question_9903.json,What animal is standing behind Lakshmana?,41,Other,animal species/type,animal,[image],[image]
27,question_16691.json,stars in 10 things i hate about you,35,Film,actor/actress (cast member),person,[text],"[image, text]"
28,question_18986.json,"Which Driver(s), in Past winners of Henry 180,...",72,Sports,driver name(s),person,[image],[image]
29,question_10541.json,when does the us open air on tv,31,Sports,TV broadcast time (date/time schedule),time,[text],[]
30,question_18965.json,when was the first year athletic trainers orga...,69,Sports,year,date/time,[text],[]
31,question_17656.json,Which player with a long beard and mustache fr...,106,Sports,football player,person,[image],[]
32,question_21958.json,In which city was the band whose members wrote...,71,Music,city,location,[text],[text]
33,question_19112.json,During the 2011-12 season in Career statistics...,129,Sports,yes/no answer,boolean,[table],[]
34,question_14280.json,"Is the red stripe on the left, center, or righ...",76,Geography,relative position (left/center/right),attribute,[image],"[image, text]"
35,question_5853.json,Eric McCormack from the TV series Perception a...,98,Television,science fiction television series,television series,[text],[text]
36,question_1175.json,"In season 2 of the Tapout TV series, who were ...",96,Television,fighters (people) featured in a TV episode,person,[table],[table]
37,question_20383.json,"was Tamil Nadu the State, in new lines of Sout...",99,Transportation,yes/no determination,boolean,[table],[table]
38,question_8638.json,who played harper on wizards of waverly place,45,Television,actor,person,[text],[text]
39,question_1160.json,How many Tony Awards have been received by the...,117,Theater,number of Tony Awards received,number,[text],[text]
40,question_6804.json,"What was the singers of ""Mera Yaar Dildaar"" in...",68,Film,singer(s) of a film song,person,[table],[table]
41,question_11373.json,Among the Argentine football teams that were r...,125,Sports,Argentine football team (club) name,sports team,[image],[]
42,question_2960.json,when does tom clancy's the division come out,44,Video games,release date,date,[text],[text]
43,question_16127.json,What are the players wearing around their neck...,101,Sports,item worn around the neck,object,[image],[image]
44,question_7962.json,What was the name of the film in which Torri H...,80,Film,film title,creative work,[table],[table]
45,question_23452.json,In what state is Alice Lioyd College and June ...,62,Geography,U.S. state,location,[text],[text]
46,question_3615.json,The 2012–13 FC Bayern Munich season was the 11...,436,Sports,name of a German top-flight football league,sports league,[text],[text]
47,question_10324.json,what was the first year of the nissan gtr,41,Transportation,first production/model year (year),year,[text],[text]
48,question_6120.json,What was the result of the Army of Conquest Al...,86,History,battle outcome/result,outcome,[table],[]
49,question_17242.json,What celestial body is on the horizon on the l...,72,Television,celestial body (object shown in logo),astronomical object,[image],[image]
50,question_11053.json,What English actor appeared in films like “The...,155,Film,English actor,person,[text],[text]
51,question_6230.json,"Which Series(s), in Television of Dave Grohl, ...",102,Television,television series title,television series,[image],[image]
52,question_12631.json,What team had a PCT of 0.611 during the regula...,72,Sports,team,organization,[table],[table]
53,question_21492.json,where is the most wine produced in the us,41,Geography,U.S. state or region (place) with highest wine...,Location,[text],[text]
54,question_10979.json,What does the person have around his hands in ...,78,Film,object around hands,object,[image],[image]
55,question_8285.json,What albums did Paul Williams release on the A...,63,Music,album titles,creative works,[table],[table]
56,question_11613.json,What is the main color in this aerial view of ...,54,Geography,color,attribute,[image],[image]
57,question_4497.json,Doctor Maya Lahan is a fictional character fro...,221,Television,television series (title),creative work,[text],[text]
58,question_3674.json,"During the season of 2019-20, how many goals d...",67,Sports,number of goals,number,[table],[table]
59,question_5929.json,who did the patriots beat in the last super bowl,48,Sports,opponent team (Super Bowl),sports team,[text],[]

In [252]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import precision_score, recall_score, f1_score

In [254]:
def calculate_metrics(dataset): 
    mlb = MultiLabelBinarizer()
    
    # Fit and transform both ground truth and predictions
    y_true = mlb.fit_transform(dataset["modality"])
    y_pred = mlb.transform(dataset["modality_answers"])
    
    precision_per_modality = precision_score(y_true, y_pred, average=None, zero_division=0)
    recall_per_modality = recall_score(y_true, y_pred, average=None, zero_division=0)
    
    print("Modalities:", mlb.classes_)
    print("Precision per modality:", precision_per_modality)
    print("Recall per modality:", recall_per_modality)

In [240]:
pk.dump(test_dataset, open("unimodal_multiple_prompts.pk", "wb"))

# Third approach: here we consider also the multimodal case

In [52]:
def dataset_build(dataset):
    image_text_rows = dataset[dataset["modality"].astype(str) == "['image', 'text']"].sample(5, random_state=42)
    text_image_rows = dataset[dataset["modality"].astype(str) == "['text', 'image']"].sample(5, random_state=42)
    image_table_rows  = dataset[dataset["modality"].astype(str) == "['image', 'table']"].sample(5, random_state=42)
    table_image_rows  = dataset[dataset["modality"].astype(str) == "['table', 'image']"].sample(5, random_state=42)
    text_table_rows  = dataset[dataset["modality"].astype(str) == "['text', 'table']"].sample(5, random_state=42)
    table_text_rows  = dataset[dataset["modality"].astype(str) == "['table', 'text']"].sample(5, random_state=42)
    table_table_rows  = dataset[dataset["modality"].astype(str) == "['table', 'table']"].sample(5, random_state=42)
    
    test_dataset = pd.concat([image_text_rows, text_image_rows, image_table_rows, table_image_rows, text_table_rows, table_text_rows, table_table_rows]) \
                   .sample(frac=1, random_state=42) \
                   .reset_index(drop=False)
    
    return test_dataset

In [53]:
multimodal_dataset = dataset_build(dataset)

In [54]:
multimodal_dataset["modality_answers"] = [[] for _ in range(len(multimodal_dataset))]

In [55]:
multimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_1269.json,Who had a hit with the artist of the music per...,160,Television,person or group (hitmaking artist),person,"[table, text]",[]
1,question_19018.json,Between the driver that is sponsored by a comp...,174,Sports,driver (person/competitor name),person,"[image, table]",[]
2,question_22384.json,At Soldier Field the Chicago Bears played agai...,150,Sports,NFL team names,sports teams,"[text, table]",[]
3,question_6153.json,Was Indiana University or the school where sci...,163,Sports,choice between two entities (yes/no comparison...,comparison outcome,"[text, table]",[]
4,question_15310.json,The venue where Sian Brooke starred in Wanderl...,78,Television,number of cars,number,"[table, image]",[]
5,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,"[table, text]",[]
6,question_2776.json,On the poster for the television show that Cha...,103,Television,time of day (as shown on a poster),time,"[table, image]",[]
7,question_9578.json,Which film title did Dick Wesson act in first:...,108,Film,film title,creative work,"[image, table]",[]
8,question_20579.json,"in Team Performance of World Club Challenge, w...",144,Sports,team (club) name,sports team,"[text, image]",[]
9,question_6113.json,What vehicle is Crash Bandicoot on the cover o...,84,Video games,vehicle (type/name shown on a cover),vehicle,"[table, image]",[]
10,question_3662.json,What's the coat color of the writer of song fo...,93,Music,coat color (color descriptor),attribute,"[text, image]",[]
11,question_10399.json,Which documentary is more recent in years in D...,136,Film,documentary film title,film,"[table, table]",[]
12,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,"[image, text]",[]
13,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,"[image, text]",[]
14,question_4356.json,Is there a soccer ball in the logo for the tea...,93,Sports,yes/no (boolean) about presence of an object i...,boolean,"[table, image]",[]
15,question_13095.json,Who does the character Sarah ultimately end up...,103,Film,character (romantic partner/spouse) name,person/character,"[table, text]",[]
16,question_2643.json,What team that Deion Sanders played for was in...,121,Sports,sports team,organization,"[text, image]",[]
17,question_18463.json,When looking at the top-scoring players in the...,168,Sports,football club/team name,organization,"[image, table]",[]
18,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,"[image, text]",[]
19,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,"[image, text]",[]
20,question_1138.json,"Was BK Derby or Djurgårdens IF, the one with l...",109,Sports,football club (team) name,organization,"[table, table]",[]
21,question_16851.json,When did 1st album of the red headed artist at...,72,Music,release date (of an album),date,"[image, text]",[]
22,question_14005.json,Was the accolade received by Natalie Wood late...,124,Film,award name (choice between two awards),award,"[table, table]",[]
23,question_8715.json,Did winner of Master's two years in a row or B...,115,Sports,person (which of two golfers),person,"[text, table]",[]
24,question_8500.json,Did Seethamma Vakitlo Sirimalle Chettu or Sari...,116,Film,film title (one of two options),Film,"[table, table]",[]
25,question_17042.json,"Among singles released by Andreas Bourani, on ...",143,Music,album title,album,"[image, table]",[]
26,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,"[text, table]",[]
27,question_9688.json,Mario Stanfield is portrayed by Jamie Hector i...,109,Television,color (of lines on title screen),attribute,"[table, image]",[]
28,question_15050.json,Which company currently owns the rights to the...,96,Theater,company (rights holder),organization,"[table, text]",[]
29,question_19883.json,Which NFL team with a logo featuring a human t...,139,Sports,NFL team,sports team,"[text, image]",[]
30,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,"[text, table]",[]
31,question_18723.json,Did Adams or Washington township in Warren Cou...,92,Geography,township (Adams or Washington) with the higher...,administrative division,"[table, table]",[]
32,question_10103.json,What player with a beard who made assists in t...,109,Sports,football (soccer) player,person,"[text, image]",[]
33,question_432.json,"In the officers' rank insignia shown here, one...",301,History,date (day-month-year) of rank achievement/prom...,date,"[image, table]",[]
34,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,"[table, text]",[]

In [11]:
derive_answers(multimodal_dataset)

NameError: name 'derive_answers' is not defined

# Fifth Approach: Multimodal with only one prompt

In [56]:
class ModalityDecision(BaseModel):
    modalities: Literal[
        "image_text",
        "image_table",
        "text_table",
        "table_table"
    ] = Field(..., description="Predicted modality combination")

In [80]:
def prompt_multimodal(question, images, paragraphs, table):
    
    images_text = "\n\n".join([
        f"{i+1}. Title: {img['title']}" 
        for i, img in enumerate(images)
    ])

    image_inputs = []
    for img in images:
        image64 = encode_image(os.path.join(FINAL_DATASET_IMAGES, img["path"]))
        image_inputs.append({
            "title": img["title"],
            "image_url": f"data:image/jpeg;base64,{image64}"
        })
        
    paragraphs_text = "\n\n".join([
        f"{i+1}. Title: {p['title']}\nContent: {p['text']}" 
        for i, p in enumerate(paragraphs)
    ])
    
    json_table = json.load(open(os.path.join(TABLE_DIR, table["json"]), "rb"))

    tables_text = f"""
    Title: {json_table["title"]}
    Content: {json_table["table"]}
    """

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """
You are a multimodal modality-selection classifier.

You will be given:
- A question
- IMAGES (titles + image content)
- TEXT paragraphs (titles + content)
- TABLES (titles + table content)

Your job is to decide which modality combination is required to answer the question.

IMPORTANT:
The output must be EXACTLY ONE of the following labels:

- image_text  (answer requires combining IMAGE + TEXT)
- image_table  (answer requires combining IMAGE + TABLE)
- text_table   (answer requires combining TEXT + TABLE)
- table_table  (answer requires combining TWO ROWS FROM THE SAME TABLE)

Rules:
- Use ONLY the provided data.
- Do NOT use outside knowledge or your knowledge.
- Do NOT guess.
- Pick the best matching combination that makes the question answerable.
- Output ONLY the label (no explanation).
"""
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": f"""
Question:
{question["original_question"]}

IMAGES:
{images_text}

TEXT paragraphs:
{paragraphs_text}

TABLES:
{tables_text}

Which modality combination is required? Return only one label.
"""
                    },
                    *[
                        {"type": "input_image", "image_url": img["image_url"]}
                        for img in image_inputs
                    ]
                ]
            }
        ],
        text_format=ModalityDecision,
    )

    return response.output_parsed.modalities

In [58]:
multimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_1269.json,Who had a hit with the artist of the music per...,160,Television,person or group (hitmaking artist),person,"[table, text]",[]
1,question_19018.json,Between the driver that is sponsored by a comp...,174,Sports,driver (person/competitor name),person,"[image, table]",[]
2,question_22384.json,At Soldier Field the Chicago Bears played agai...,150,Sports,NFL team names,sports teams,"[text, table]",[]
3,question_6153.json,Was Indiana University or the school where sci...,163,Sports,choice between two entities (yes/no comparison...,comparison outcome,"[text, table]",[]
4,question_15310.json,The venue where Sian Brooke starred in Wanderl...,78,Television,number of cars,number,"[table, image]",[]
5,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,"[table, text]",[]
6,question_2776.json,On the poster for the television show that Cha...,103,Television,time of day (as shown on a poster),time,"[table, image]",[]
7,question_9578.json,Which film title did Dick Wesson act in first:...,108,Film,film title,creative work,"[image, table]",[]
8,question_20579.json,"in Team Performance of World Club Challenge, w...",144,Sports,team (club) name,sports team,"[text, image]",[]
9,question_6113.json,What vehicle is Crash Bandicoot on the cover o...,84,Video games,vehicle (type/name shown on a cover),vehicle,"[table, image]",[]
10,question_3662.json,What's the coat color of the writer of song fo...,93,Music,coat color (color descriptor),attribute,"[text, image]",[]
11,question_10399.json,Which documentary is more recent in years in D...,136,Film,documentary film title,film,"[table, table]",[]
12,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,"[image, text]",[]
13,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,"[image, text]",[]
14,question_4356.json,Is there a soccer ball in the logo for the tea...,93,Sports,yes/no (boolean) about presence of an object i...,boolean,"[table, image]",[]
15,question_13095.json,Who does the character Sarah ultimately end up...,103,Film,character (romantic partner/spouse) name,person/character,"[table, text]",[]
16,question_2643.json,What team that Deion Sanders played for was in...,121,Sports,sports team,organization,"[text, image]",[]
17,question_18463.json,When looking at the top-scoring players in the...,168,Sports,football club/team name,organization,"[image, table]",[]
18,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,"[image, text]",[]
19,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,"[image, text]",[]
20,question_1138.json,"Was BK Derby or Djurgårdens IF, the one with l...",109,Sports,football club (team) name,organization,"[table, table]",[]
21,question_16851.json,When did 1st album of the red headed artist at...,72,Music,release date (of an album),date,"[image, text]",[]
22,question_14005.json,Was the accolade received by Natalie Wood late...,124,Film,award name (choice between two awards),award,"[table, table]",[]
23,question_8715.json,Did winner of Master's two years in a row or B...,115,Sports,person (which of two golfers),person,"[text, table]",[]
24,question_8500.json,Did Seethamma Vakitlo Sirimalle Chettu or Sari...,116,Film,film title (one of two options),Film,"[table, table]",[]
25,question_17042.json,"Among singles released by Andreas Bourani, on ...",143,Music,album title,album,"[image, table]",[]
26,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,"[text, table]",[]
27,question_9688.json,Mario Stanfield is portrayed by Jamie Hector i...,109,Television,color (of lines on title screen),attribute,"[table, image]",[]
28,question_15050.json,Which company currently owns the rights to the...,96,Theater,company (rights holder),organization,"[table, text]",[]
29,question_19883.json,Which NFL team with a logo featuring a human t...,139,Sports,NFL team,sports team,"[text, image]",[]
30,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,"[text, table]",[]
31,question_18723.json,Did Adams or Washington township in Warren Cou...,92,Geography,township (Adams or Washington) with the higher...,administrative division,"[table, table]",[]
32,question_10103.json,What player with a beard who made assists in t...,109,Sports,football (soccer) player,person,"[text, image]",[]
33,question_432.json,"In the officers' rank insignia shown here, one...",301,History,date (day-month-year) of rank achievement/prom...,date,"[image, table]",[]
34,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,"[table, text]",[]

In [81]:
def derive_answers_multimodal_one_prompt(dataset): 
    for i, question in dataset.iterrows(): 
        print(f"Question number: {i}, Question JSON: {question['index']}, Question: {question['original_question']}")
        json_association = json.load(open(os.path.join(ASSOCIATION_DIR, question["index"]), "rb"))
        
        image_set = json_association["image_set"]
        text_set = json_association["text_set"]
        table_set = json_association["table_set"][0]
        
        modality_answer = prompt_multimodal(question, image_set, text_set, table_set)
        
        print("Answer for images: ", modality_answer)
        
        dataset.at[i, "modality_answers"] = modality_answer

In [60]:
derive_answers_multimodal_one_prompt(multimodal_dataset)

Question number: 0, Question JSON: question_1269.json, Question: Who had a hit with the artist of the music performed during Magic Moments of Week 7 of season 6 of the German Let's dance when the score was 16 (7,5,4) in 2012?
Answer for images:  text_table
Question number: 1, Question JSON: question_19018.json, Question: Between the driver that is sponsored by a company with a yellow triangle logo below its name and Matt Kenseth, which driver had the lowest position in the 2014 Brickyard 400?
Answer for images:  image_table
Question number: 2, Question JSON: question_22384.json, Question: At Soldier Field the Chicago Bears played against what teams that have won the most Super Bowls in a row during their regular season schedule of 1995?
Answer for images:  text_table
Question number: 3, Question JSON: question_6153.json, Question: Was Indiana University or the school where scientists built the first nanotube computer associated with a lower pick in the first round of the 2011 MLS SuperDraft?
Answer for images:  text_table
Question number: 4, Question JSON: question_15310.json, Question: The venue where Sian Brooke starred in Wanderlust has how many cars out front?
Answer for images:  image_table
Question number: 5, Question JSON: question_6883.json, Question: Does Hilary Duff sing in the movie where T.J. Thyne played the Emcee?
Answer for images:  text_table
Question number: 6, Question JSON: question_2776.json, Question: On the poster for the television show that Charlie Day appeared on in 2011, what time of the day is it?
Answer for images:  image_table
Question number: 7, Question JSON: question_9578.json, Question: Which film title did Dick Wesson act in first:  The title with a poster featuring a rocket or Calamity Jane?
Answer for images:  image_table
Question number: 8, Question JSON: question_20579.json, Question: in Team Performance of World Club Challenge, who is playing at the nrl grand final and was the team which have bird beaks visible in their logo?
Answer for images:  image_table
Question number: 9, Question JSON: question_6113.json, Question: What vehicle is Crash Bandicoot on the cover of the 1998 M. Mothersbaugh video game?
Answer for images:  image_table
Question number: 10, Question JSON: question_3662.json, Question: What's the coat color of the writer of song for wachet auf (sleepers awake) and chorale text?
Answer for images:  image_text
Question number: 11, Question JSON: question_10399.json, Question: Which documentary is more recent in years in Documentaries of Robert De Niro filmography, More than a Movie or Biography: Liza Minnelli?
Answer for images:  table_table
Question number: 12, Question JSON: question_22206.json, Question: Which location won a LEAF Award first:  Where they went it pitch perfect 2 or the location featuring a skyscraper with an open section by its roof, resembling a bottle opener?
Answer for images:  image_text
Question number: 13, Question JSON: question_3021.json, Question: What is the meaning of the colors of the flag with three horizontal stripes from the country who competed in the Mens pole vault finals at the European Athletics U23 Championships in 2011?
Answer for images:  text_table
Question number: 14, Question JSON: question_4356.json, Question: Is there a soccer ball in the logo for the team that Aron Elís Þrándarson played for in 2011?
Answer for images:  image_table
Question number: 15, Question JSON: question_13095.json, Question: Who does the character Sarah ultimately end up with in the film that featured Patrick Fabian as Donald?
Answer for images:  text_table
Question number: 16, Question JSON: question_2643.json, Question: What team that Deion Sanders played for was in the Northern Iowa Panthers NFL draft with a face of a human on their logo?
Answer for images:  image_text
Question number: 17, Question JSON: question_18463.json, Question: When looking at the top-scoring players in the Bundesliga's 2005-06 season, which team has more goals listed: Borussia Dortmund, or the team whose logo features a goat?
Answer for images:  image_table
Question number: 18, Question JSON: question_16282.json, Question: The female artist with long brown hair extending past her shoulders that has the most number-one songs on the German airplay chart sings the song wild thoughts featuring who on the guitar?
Answer for images:  image_text
Question number: 19, Question JSON: question_19723.json, Question: in Los Angeles Chargers of List of NFL playoff games, when did the opponent that has a horse in logo, change their logo?
Answer for images:  text_table
Question number: 20, Question JSON: question_1138.json, Question: Was BK Derby or Djurgårdens IF, the one with lower points in Division 2 Östra of 1933–34 in Swedish football?
Answer for images:  table_table
Question number: 21, Question JSON: question_16851.json, Question: When did 1st album of the red headed artist at the Parque Viva come out?
Answer for images:  image_text
Question number: 22, Question JSON: question_14005.json, Question: Was the accolade received by Natalie Wood latest in her career the Star of Tomorrow award or the Best Foreign actress award?
Answer for images:  table_table
Question number: 23, Question JSON: question_8715.json, Question: Did winner of Master's two years in a row or Bernhard Langer have lower Order of Merit 1991 European Tour position?
Answer for images:  text_table
Question number: 24, Question JSON: question_8500.json, Question: Did Seethamma Vakitlo Sirimalle Chettu or Sarileru Neekevvaru come out more recently of Satyadev Kancharana's films?
Answer for images:  table_table
Question number: 25, Question JSON: question_17042.json, Question: Among singles released by Andreas Bourani, on what album would you find the song whose cover (as a single) has a man wearing a striped sweater?
Answer for images:  image_table
Question number: 26, Question JSON: question_17225.json, Question: Which 1999 European Seniors tournament was hosted by the country dubbed "Celtic Tiger" by economists?
Answer for images:  text_table
Question number: 27, Question JSON: question_9688.json, Question: Mario Stanfield is portrayed by Jamie Hector is a show with what color lines running across the title screen?
Answer for images:  image_table
Question number: 28, Question JSON: question_15050.json, Question: Which company currently owns the rights to the play in which Song Won-geun played Sky Masterson?
Answer for images:  text_table
Question number: 29, Question JSON: question_19883.json, Question: Which NFL team with a logo featuring a human that lost to the Oakland Raiders in the 2017 season was also the team Roman Reigns played for?
Answer for images:  image_text
Question number: 30, Question JSON: question_12447.json, Question: The song "With a Flair" was written for a 1971 Disney musical that was based on the books "The Magic Bedknob; or, How to Become a Witch in Ten Easy Lessons" and "Bonfires and Broomsticks".  What part did Tessie O'Shea play in this movie?
Answer for images:  text_table
Question number: 31, Question JSON: question_18723.json, Question: Did Adams or Washington township in Warren County, Indiana have a higher population in 2010?
Answer for images:  table_table
Question number: 32, Question JSON: question_10103.json, Question: What player with a beard who made assists in the La Liga of 2010-11 has also won the most golden boot awards?
Answer for images:  image_text
Question number: 33, Question JSON: question_432.json, Question: In the officers' rank insignia shown here, one such rank whose insignia features three stars above a pair of crossed swords.  On what date did Iqroop Singh Ghuman achieve, in his nation's army, the rank that consists of two hyphenated words: "Lieutenant" followed by the word that was just alluded to?
Answer for images:  image_table
Question number: 34, Question JSON: question_2526.json, Question: What date did the first episode of the show starring Jillian Claire as Abigail Deveraux air?
Answer for images:  text_table

In [61]:
multimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_1269.json,Who had a hit with the artist of the music per...,160,Television,person or group (hitmaking artist),person,"[table, text]",text_table
1,question_19018.json,Between the driver that is sponsored by a comp...,174,Sports,driver (person/competitor name),person,"[image, table]",image_table
2,question_22384.json,At Soldier Field the Chicago Bears played agai...,150,Sports,NFL team names,sports teams,"[text, table]",text_table
3,question_6153.json,Was Indiana University or the school where sci...,163,Sports,choice between two entities (yes/no comparison...,comparison outcome,"[text, table]",text_table
4,question_15310.json,The venue where Sian Brooke starred in Wanderl...,78,Television,number of cars,number,"[table, image]",image_table
5,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,"[table, text]",text_table
6,question_2776.json,On the poster for the television show that Cha...,103,Television,time of day (as shown on a poster),time,"[table, image]",image_table
7,question_9578.json,Which film title did Dick Wesson act in first:...,108,Film,film title,creative work,"[image, table]",image_table
8,question_20579.json,"in Team Performance of World Club Challenge, w...",144,Sports,team (club) name,sports team,"[text, image]",image_table
9,question_6113.json,What vehicle is Crash Bandicoot on the cover o...,84,Video games,vehicle (type/name shown on a cover),vehicle,"[table, image]",image_table
10,question_3662.json,What's the coat color of the writer of song fo...,93,Music,coat color (color descriptor),attribute,"[text, image]",image_text
11,question_10399.json,Which documentary is more recent in years in D...,136,Film,documentary film title,film,"[table, table]",table_table
12,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,"[image, text]",image_text
13,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,"[image, text]",text_table
14,question_4356.json,Is there a soccer ball in the logo for the tea...,93,Sports,yes/no (boolean) about presence of an object i...,boolean,"[table, image]",image_table
15,question_13095.json,Who does the character Sarah ultimately end up...,103,Film,character (romantic partner/spouse) name,person/character,"[table, text]",text_table
16,question_2643.json,What team that Deion Sanders played for was in...,121,Sports,sports team,organization,"[text, image]",image_text
17,question_18463.json,When looking at the top-scoring players in the...,168,Sports,football club/team name,organization,"[image, table]",image_table
18,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,"[image, text]",image_text
19,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,"[image, text]",text_table
20,question_1138.json,"Was BK Derby or Djurgårdens IF, the one with l...",109,Sports,football club (team) name,organization,"[table, table]",table_table
21,question_16851.json,When did 1st album of the red headed artist at...,72,Music,release date (of an album),date,"[image, text]",image_text
22,question_14005.json,Was the accolade received by Natalie Wood late...,124,Film,award name (choice between two awards),award,"[table, table]",table_table
23,question_8715.json,Did winner of Master's two years in a row or B...,115,Sports,person (which of two golfers),person,"[text, table]",text_table
24,question_8500.json,Did Seethamma Vakitlo Sirimalle Chettu or Sari...,116,Film,film title (one of two options),Film,"[table, table]",table_table
25,question_17042.json,"Among singles released by Andreas Bourani, on ...",143,Music,album title,album,"[image, table]",image_table
26,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,"[text, table]",text_table
27,question_9688.json,Mario Stanfield is portrayed by Jamie Hector i...,109,Television,color (of lines on title screen),attribute,"[table, image]",image_table
28,question_15050.json,Which company currently owns the rights to the...,96,Theater,company (rights holder),organization,"[table, text]",text_table
29,question_19883.json,Which NFL team with a logo featuring a human t...,139,Sports,NFL team,sports team,"[text, image]",image_text
30,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,"[text, table]",text_table
31,question_18723.json,Did Adams or Washington township in Warren Cou...,92,Geography,township (Adams or Washington) with the higher...,administrative division,"[table, table]",table_table
32,question_10103.json,What player with a beard who made assists in t...,109,Sports,football (soccer) player,person,"[text, image]",image_text
33,question_432.json,"In the officers' rank insignia shown here, one...",301,History,date (day-month-year) of rank achievement/prom...,date,"[image, table]",image_table
34,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,"[table, text]",text_table

In [62]:
pk.dump(multimodal_dataset, open("multimodal_one_prompt.pk", "wb"))

In [44]:
multimodal_dataset = pk.load(open("multimodal_one_prompt.pk", "rb"))

In [63]:
multimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_1269.json,Who had a hit with the artist of the music per...,160,Television,person or group (hitmaking artist),person,"[table, text]",text_table
1,question_19018.json,Between the driver that is sponsored by a comp...,174,Sports,driver (person/competitor name),person,"[image, table]",image_table
2,question_22384.json,At Soldier Field the Chicago Bears played agai...,150,Sports,NFL team names,sports teams,"[text, table]",text_table
3,question_6153.json,Was Indiana University or the school where sci...,163,Sports,choice between two entities (yes/no comparison...,comparison outcome,"[text, table]",text_table
4,question_15310.json,The venue where Sian Brooke starred in Wanderl...,78,Television,number of cars,number,"[table, image]",image_table
5,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,"[table, text]",text_table
6,question_2776.json,On the poster for the television show that Cha...,103,Television,time of day (as shown on a poster),time,"[table, image]",image_table
7,question_9578.json,Which film title did Dick Wesson act in first:...,108,Film,film title,creative work,"[image, table]",image_table
8,question_20579.json,"in Team Performance of World Club Challenge, w...",144,Sports,team (club) name,sports team,"[text, image]",image_table
9,question_6113.json,What vehicle is Crash Bandicoot on the cover o...,84,Video games,vehicle (type/name shown on a cover),vehicle,"[table, image]",image_table
10,question_3662.json,What's the coat color of the writer of song fo...,93,Music,coat color (color descriptor),attribute,"[text, image]",image_text
11,question_10399.json,Which documentary is more recent in years in D...,136,Film,documentary film title,film,"[table, table]",table_table
12,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,"[image, text]",image_text
13,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,"[image, text]",text_table
14,question_4356.json,Is there a soccer ball in the logo for the tea...,93,Sports,yes/no (boolean) about presence of an object i...,boolean,"[table, image]",image_table
15,question_13095.json,Who does the character Sarah ultimately end up...,103,Film,character (romantic partner/spouse) name,person/character,"[table, text]",text_table
16,question_2643.json,What team that Deion Sanders played for was in...,121,Sports,sports team,organization,"[text, image]",image_text
17,question_18463.json,When looking at the top-scoring players in the...,168,Sports,football club/team name,organization,"[image, table]",image_table
18,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,"[image, text]",image_text
19,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,"[image, text]",text_table
20,question_1138.json,"Was BK Derby or Djurgårdens IF, the one with l...",109,Sports,football club (team) name,organization,"[table, table]",table_table
21,question_16851.json,When did 1st album of the red headed artist at...,72,Music,release date (of an album),date,"[image, text]",image_text
22,question_14005.json,Was the accolade received by Natalie Wood late...,124,Film,award name (choice between two awards),award,"[table, table]",table_table
23,question_8715.json,Did winner of Master's two years in a row or B...,115,Sports,person (which of two golfers),person,"[text, table]",text_table
24,question_8500.json,Did Seethamma Vakitlo Sirimalle Chettu or Sari...,116,Film,film title (one of two options),Film,"[table, table]",table_table
25,question_17042.json,"Among singles released by Andreas Bourani, on ...",143,Music,album title,album,"[image, table]",image_table
26,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,"[text, table]",text_table
27,question_9688.json,Mario Stanfield is portrayed by Jamie Hector i...,109,Television,color (of lines on title screen),attribute,"[table, image]",image_table
28,question_15050.json,Which company currently owns the rights to the...,96,Theater,company (rights holder),organization,"[table, text]",text_table
29,question_19883.json,Which NFL team with a logo featuring a human t...,139,Sports,NFL team,sports team,"[text, image]",image_text
30,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,"[text, table]",text_table
31,question_18723.json,Did Adams or Washington township in Warren Cou...,92,Geography,township (Adams or Washington) with the higher...,administrative division,"[table, table]",table_table
32,question_10103.json,What player with a beard who made assists in t...,109,Sports,football (soccer) player,person,"[text, image]",image_text
33,question_432.json,"In the officers' rank insignia shown here, one...",301,History,date (day-month-year) of rank achievement/prom...,date,"[image, table]",image_table
34,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,"[table, text]",text_table

In [22]:
def normalize_combo(x):
    if isinstance(x, list): 
        return "_".join(sorted(x)) 
    elif isinstance(x, str): 
        return '_'.join(sorted(x.split('_')))

In [65]:
multimodal_dataset["modality"] = multimodal_dataset["modality"].apply(normalize_combo)
multimodal_dataset["modality_answers"] = multimodal_dataset["modality_answers"].apply(normalize_combo)

In [66]:
multimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_1269.json,Who had a hit with the artist of the music per...,160,Television,person or group (hitmaking artist),person,table_text,table_text
1,question_19018.json,Between the driver that is sponsored by a comp...,174,Sports,driver (person/competitor name),person,image_table,image_table
2,question_22384.json,At Soldier Field the Chicago Bears played agai...,150,Sports,NFL team names,sports teams,table_text,table_text
3,question_6153.json,Was Indiana University or the school where sci...,163,Sports,choice between two entities (yes/no comparison...,comparison outcome,table_text,table_text
4,question_15310.json,The venue where Sian Brooke starred in Wanderl...,78,Television,number of cars,number,image_table,image_table
5,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,table_text,table_text
6,question_2776.json,On the poster for the television show that Cha...,103,Television,time of day (as shown on a poster),time,image_table,image_table
7,question_9578.json,Which film title did Dick Wesson act in first:...,108,Film,film title,creative work,image_table,image_table
8,question_20579.json,"in Team Performance of World Club Challenge, w...",144,Sports,team (club) name,sports team,image_text,image_table
9,question_6113.json,What vehicle is Crash Bandicoot on the cover o...,84,Video games,vehicle (type/name shown on a cover),vehicle,image_table,image_table
10,question_3662.json,What's the coat color of the writer of song fo...,93,Music,coat color (color descriptor),attribute,image_text,image_text
11,question_10399.json,Which documentary is more recent in years in D...,136,Film,documentary film title,film,table_table,table_table
12,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,image_text,image_text
13,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,image_text,table_text
14,question_4356.json,Is there a soccer ball in the logo for the tea...,93,Sports,yes/no (boolean) about presence of an object i...,boolean,image_table,image_table
15,question_13095.json,Who does the character Sarah ultimately end up...,103,Film,character (romantic partner/spouse) name,person/character,table_text,table_text
16,question_2643.json,What team that Deion Sanders played for was in...,121,Sports,sports team,organization,image_text,image_text
17,question_18463.json,When looking at the top-scoring players in the...,168,Sports,football club/team name,organization,image_table,image_table
18,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,image_text,image_text
19,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,image_text,table_text
20,question_1138.json,"Was BK Derby or Djurgårdens IF, the one with l...",109,Sports,football club (team) name,organization,table_table,table_table
21,question_16851.json,When did 1st album of the red headed artist at...,72,Music,release date (of an album),date,image_text,image_text
22,question_14005.json,Was the accolade received by Natalie Wood late...,124,Film,award name (choice between two awards),award,table_table,table_table
23,question_8715.json,Did winner of Master's two years in a row or B...,115,Sports,person (which of two golfers),person,table_text,table_text
24,question_8500.json,Did Seethamma Vakitlo Sirimalle Chettu or Sari...,116,Film,film title (one of two options),Film,table_table,table_table
25,question_17042.json,"Among singles released by Andreas Bourani, on ...",143,Music,album title,album,image_table,image_table
26,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,table_text,table_text
27,question_9688.json,Mario Stanfield is portrayed by Jamie Hector i...,109,Television,color (of lines on title screen),attribute,image_table,image_table
28,question_15050.json,Which company currently owns the rights to the...,96,Theater,company (rights holder),organization,table_text,table_text
29,question_19883.json,Which NFL team with a logo featuring a human t...,139,Sports,NFL team,sports team,image_text,image_text
30,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,table_text,table_text
31,question_18723.json,Did Adams or Washington township in Warren Cou...,92,Geography,township (Adams or Washington) with the higher...,administrative division,table_table,table_table
32,question_10103.json,What player with a beard who made assists in t...,109,Sports,football (soccer) player,person,image_text,image_text
33,question_432.json,"In the officers' rank insignia shown here, one...",301,History,date (day-month-year) of rank achievement/prom...,date,image_table,image_table
34,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,table_text,table_text

In [67]:
labels = sorted(set(multimodal_dataset["modality"]))

print(labels)

results = {}

for label in labels:
    tp = fp = fn = 0
    
    for _, row in multimodal_dataset.iterrows():
        gt = row["modality"]
        pred = row["modality_answers"]
        
        if pred == label and gt == label:
            tp += 1
        elif pred == label and gt != label:
            fp += 1
        elif pred != label and gt == label:
            fn += 1
    
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1        = (2*precision*recall/(precision+recall)) if (precision+recall) > 0 else 0
    
    results[label] = {
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

['image_table', 'image_text', 'table_table', 'table_text']

In [69]:
pd.DataFrame(results)

           image_table  image_text  table_table  table_text
TP           10.000000    7.000000          5.0   10.000000
FP            1.000000    0.000000          0.0    2.000000
FN            0.000000    3.000000          0.0    0.000000
precision     0.909091    1.000000          1.0    0.833333
recall        1.000000    0.700000          1.0    1.000000
f1            0.952381    0.823529          1.0    0.909091

# Sixth Approach: Unimodal and Multimodal with only one prompt

In [7]:
def dataset_build(dataset):
    image_rows = dataset[dataset["modality"].astype(str) == "['image']"].sample(7, random_state=42)
    text_rows  = dataset[dataset["modality"].astype(str) == "['text']"].sample(7, random_state=42)
    table_rows = dataset[dataset["modality"].astype(str) == "['table']"].sample(7, random_state=42)
    
    image_text_rows = dataset[dataset["modality"].astype(str) == "['image', 'text']"].sample(7, random_state=42)
    text_image_rows = dataset[dataset["modality"].astype(str) == "['text', 'image']"].sample(7, random_state=42)
    image_table_rows  = dataset[dataset["modality"].astype(str) == "['image', 'table']"].sample(7, random_state=42)
    table_image_rows  = dataset[dataset["modality"].astype(str) == "['table', 'image']"].sample(7, random_state=42)
    
    text_table_rows  = dataset[dataset["modality"].astype(str) == "['text', 'table']"].sample(7, random_state=42)
    table_text_rows  = dataset[dataset["modality"].astype(str) == "['table', 'text']"].sample(7, random_state=42)
    
    table_table_rows  = dataset[dataset["modality"].astype(str) == "['table', 'table']"].sample(7, random_state=42)
    
    test_dataset = pd.concat([image_rows, text_rows, table_rows, image_text_rows, text_image_rows, image_table_rows, table_image_rows, text_table_rows, table_text_rows, table_table_rows]) \
                   .sample(frac=1, random_state=42) \
                   .reset_index(drop=False)
    
    return test_dataset

In [8]:
multimodal_unimodal_dataset = dataset_build(dataset)

In [9]:
multimodal_unimodal_dataset["modality_answers"] = [[] for _ in range(len(multimodal_unimodal_dataset))]

In [10]:
class ModalityDecision(BaseModel):
    modalities: Literal[
        "image", 
        "text", 
        "table",
        "image_text",
        "image_table",
        "text_table",
    ] = Field(..., description="Predicted modality combination")

In [11]:
def prompt_all(question, images, paragraphs, table):
    
    images_text = "\n\n".join([
        f"{i+1}. Title: {img['title']}" 
        for i, img in enumerate(images)
    ])

    image_inputs = []
    for img in images:
        image64 = encode_image(os.path.join(FINAL_DATASET_IMAGES, img["path"]))
        image_inputs.append({
            "title": img["title"],
            "image_url": f"data:image/jpeg;base64,{image64}"
        })
        
    paragraphs_text = "\n\n".join([
        f"{i+1}. Title: {p['title']}\nContent: {p['text']}" 
        for i, p in enumerate(paragraphs)
    ])
    
    json_table = json.load(open(os.path.join(TABLE_DIR, table["json"]), "rb"))

    tables_text = f"""
    Title: {json_table["title"]}
    Table name: {json_table["table_name"]}
    Content: {json_table["table"]}
    """

    response = client.responses.parse(
        model="gpt-5.2",
        input=[
            {
                "role": "system",
                "content": """
You are a multimodal modality-selection classifier.

You will be given:
- A question
- IMAGES (titles + image content)
- TEXT paragraphs (titles + content)
- TABLES (titles + table content)

Your job is to decide which modality combination is required to answer the question.

IMPORTANT:
The output must be EXACTLY ONE of the following labels:
- image          (answer can be derived from image alone)
- text           (answer can be derived from text alone)
- table          (answer can be derived from table alone)
- image_text     (answer requires combining IMAGE + TEXT)
- image_table    (answer requires combining IMAGE + TABLE)
- text_table     (answer requires combining TEXT + TABLE)

Rules:
- Use ONLY the provided data.
- Do NOT use outside knowledge or your knowledge.
- Do NOT guess.
- Pick the best matching label.
- Output ONLY the label (no explanation).
"""
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": f"""
Question:
{question["original_question"]}

IMAGES:
{images_text}

TEXT paragraphs:
{paragraphs_text}

TABLES:
{tables_text}

Which modality or modality combination is required? Return only one label.
"""
                    },
                    *[
                        {"type": "input_image", "image_url": img["image_url"]}
                        for img in image_inputs
                    ]
                ]
            }
        ],
        text_format=ModalityDecision,
    )

    return response.output_parsed.modalities

In [12]:
def derive_answers_all_one_prompt(dataset): 
    for i, question in dataset.iterrows(): 
        print(f"Question number: {i}, Question JSON: {question['index']}, Question: {question['original_question']}")
        json_association = json.load(open(os.path.join(ASSOCIATION_DIR, question["index"]), "rb"))
        
        image_set = json_association["image_set"]
        text_set = json_association["text_set"]
        table_set = json_association["table_set"][0]
        
        modality_answer = prompt_all(question, image_set, text_set, table_set)
        
        print("Answer for images: ", modality_answer)
        
        dataset.at[i, "modality_answers"] = modality_answer

In [16]:
derive_answers_all_one_prompt(multimodal_unimodal_dataset)

Question number: 0, Question JSON: question_16282.json, Question: The female artist with long brown hair extending past her shoulders that has the most number-one songs on the German airplay chart sings the song wild thoughts featuring who on the guitar?
Answer for images:  image_table
Question number: 1, Question JSON: question_13547.json, Question: What object is seen in the center of the Days of Our Lives poster?
Answer for images:  image
Question number: 2, Question JSON: question_12447.json, Question: The song "With a Flair" was written for a 1971 Disney musical that was based on the books "The Magic Bedknob; or, How to Become a Witch in Ten Easy Lessons" and "Bonfires and Broomsticks".  What part did Tessie O'Shea play in this movie?
Answer for images:  table
Question number: 3, Question JSON: question_17634.json, Question: Which location with red seating areas is where Ashley Moloney made personal bests?
Answer for images:  image_table
Question number: 4, Question JSON: question_6353.json, Question: What team played the Seattle Seahawks in the 1995 regular season when the kickoff was 10:00am PST that was also one of the two teams that played in the first super bowl?
Answer for images:  text_table
Question number: 5, Question JSON: question_6804.json, Question: What was the singers of "Mera Yaar Dildaar" in Jaanwar in 1999 film?
Answer for images:  table
Question number: 6, Question JSON: question_10324.json, Question: what was the first year of the nissan gtr
Answer for images:  text
Question number: 7, Question JSON: question_17568.json, Question: In the location out of surrey or london of kingston upon thames, the middle right picture shows which type of wheel?
Answer for images:  image
Question number: 8, Question JSON: question_9688.json, Question: Mario Stanfield is portrayed by Jamie Hector is a show with what color lines running across the title screen?
Answer for images:  image_table
Question number: 9, Question JSON: question_15730.json, Question: who won the world best player of the year 2018
Answer for images:  text
Question number: 10, Question JSON: question_20579.json, Question: in Team Performance of World Club Challenge, who is playing at the nrl grand final and was the team which have bird beaks visible in their logo?
Answer for images:  image_text
Question number: 11, Question JSON: question_11053.json, Question: What English actor appeared in films like “The Invisible Man” and “Robin Hood” while costarring with Lon Chaney JR in the 1941 edition of “The Wolf a man”?
Answer for images:  text
Question number: 12, Question JSON: question_18723.json, Question: Did Adams or Washington township in Warren County, Indiana have a higher population in 2010?
Answer for images:  table
Question number: 13, Question JSON: question_14691.json, Question: How many people are wearing a black and red striped shirt in the Association football photo?
Answer for images:  image
Question number: 14, Question JSON: question_16843.json, Question: Levi risamasu played for the professional football club in which country before being transferred to the team in the Eerste Divisie whose manager was replaced by Ulderink in 2012-13?
Answer for images:  text_table
Question number: 15, Question JSON: question_10103.json, Question: What player with a beard who made assists in the La Liga of 2010-11 has also won the most golden boot awards?
Answer for images:  image_text
Question number: 16, Question JSON: question_13095.json, Question: Who does the character Sarah ultimately end up with in the film that featured Patrick Fabian as Donald?
Answer for images:  text_table
Question number: 17, Question JSON: question_17042.json, Question: Among singles released by Andreas Bourani, on what album would you find the song whose cover (as a single) has a man wearing a striped sweater?
Answer for images:  image_table
Question number: 18, Question JSON: question_1269.json, Question: Who had a hit with the artist of the music performed during Magic Moments of Week 7 of season 6 of the German Let's dance when the score was 16 (7,5,4) in 2012?
Answer for images:  text_table
Question number: 19, Question JSON: question_1513.json, Question: What color are the men's jackets in the 2011 drama series with Alan Shirahama?
Answer for images:  image_table
Question number: 20, Question JSON: question_8285.json, Question: What albums did Paul Williams release on the A&M label in 1974?
Answer for images:  table
Question number: 21, Question JSON: question_5568.json, Question: In this collage featuring the city matt saracen went to in season 4, how many photos are present?
Answer for images:  image_text
Question number: 22, Question JSON: question_15310.json, Question: The venue where Sian Brooke starred in Wanderlust has how many cars out front?
Answer for images:  image_table
Question number: 23, Question JSON: question_2643.json, Question: What team that Deion Sanders played for was in the Northern Iowa Panthers NFL draft with a face of a human on their logo?
Answer for images:  image_text
Question number: 24, Question JSON: question_21492.json, Question: where is the most wine produced in the us
Answer for images:  text
Question number: 25, Question JSON: question_22384.json, Question: At Soldier Field the Chicago Bears played against what teams that have won the most Super Bowls in a row during their regular season schedule of 1995?
Answer for images:  text_table
Question number: 26, Question JSON: question_21617.json, Question: Did the player with a 2018 team of the New York Jets or the team with a horse in its logo have a higher age among the players listed in the Departures of the 2018 Cincinnati Bengals season?
Answer for images:  image_table
Question number: 27, Question JSON: question_4356.json, Question: Is there a soccer ball in the logo for the team that Aron Elís Þrándarson played for in 2011?
Answer for images:  image_table
Question number: 28, Question JSON: question_2776.json, Question: On the poster for the television show that Charlie Day appeared on in 2011, what time of the day is it?
Answer for images:  image_table
Question number: 29, Question JSON: question_11881.json, Question: was Tha Eastsidaz the Featuring, in track listing of You Better Believe It when the Album was Likwidation?
Answer for images:  table
Question number: 30, Question JSON: question_15050.json, Question: Which company currently owns the rights to the play in which Song Won-geun played Sky Masterson?
Answer for images:  text_table
Question number: 31, Question JSON: question_432.json, Question: In the officers' rank insignia shown here, one such rank whose insignia features three stars above a pair of crossed swords.  On what date did Iqroop Singh Ghuman achieve, in his nation's army, the rank that consists of two hyphenated words: "Lieutenant" followed by the word that was just alluded to?
Answer for images:  image_table
Question number: 32, Question JSON: question_3021.json, Question: What is the meaning of the colors of the flag with three horizontal stripes from the country who competed in the Mens pole vault finals at the European Athletics U23 Championships in 2011?
Answer for images:  text_table
Question number: 33, Question JSON: question_19018.json, Question: Between the driver that is sponsored by a company with a yellow triangle logo below its name and Matt Kenseth, which driver had the lowest position in the 2014 Brickyard 400?
Answer for images:  image_table
Question number: 34, Question JSON: question_18965.json, Question: when was the first year athletic trainers organized into a profession
Answer for images:  text
Question number: 35, Question JSON: question_6153.json, Question: Was Indiana University or the school where scientists built the first nanotube computer associated with a lower pick in the first round of the 2011 MLS SuperDraft?
Answer for images:  text_table
Question number: 36, Question JSON: question_1705.json, Question: What main color besides purple makes up the uniform for the 2014 Minnesota Vikings season?
Answer for images:  image
Question number: 37, Question JSON: question_18327.json, Question: What team did Fred Durrant play on during the 1948-49 season?
Answer for images:  table
Question number: 38, Question JSON: question_2960.json, Question: when does tom clancy's the division come out
Answer for images:  text
Question number: 39, Question JSON: question_18476.json, Question: in Schedule of 1984 New Orleans Saints season, who did deion sanders play for in the nfl and was the Opponent when the Result was W 17–13?
Answer for images:  text_table
Question number: 40, Question JSON: question_1820.json, Question: What color are the tree leaves in this photo of Macon, Georgia?
Answer for images:  image
Question number: 41, Question JSON: question_18463.json, Question: When looking at the top-scoring players in the Bundesliga's 2005-06 season, which team has more goals listed: Borussia Dortmund, or the team whose logo features a goat?
Answer for images:  image_table
Question number: 42, Question JSON: question_8500.json, Question: Did Seethamma Vakitlo Sirimalle Chettu or Sarileru Neekevvaru come out more recently of Satyadev Kancharana's films?
Answer for images:  table
Question number: 43, Question JSON: question_1283.json, Question: Did NFL player Kenoy Kennedy have more tackles in 2000 or 2003?
Answer for images:  table
Question number: 44, Question JSON: question_21279.json, Question: Which player with top assists in the Portland Timbers season of 2019 has a lower U.S. Open Cup:  Jeremy Ebobisse or Andy Polo?
Answer for images:  table
Question number: 45, Question JSON: question_20383.json, Question: was Tamil Nadu the State, in new lines of Southern Railway zone when the Status was Under progress?
Answer for images:  table
Question number: 46, Question JSON: question_8874.json, Question: Which video game title was Danielle Nicolet a voice actor for first:  The title with a cover featuring a badge with a shield shaped center or the newest grand theft auto for ps4?
Answer for images:  image_table
Question number: 47, Question JSON: question_23570.json, Question: Does Paraná or the state with a star in the lower-right corner of its flag have more Miss Brasil title wins?
Answer for images:  image_table
Question number: 48, Question JSON: question_14856.json, Question: What are the names of the colosseum in the city in which Italian athletes competed in a marathon and which also has two statues of angels facing toward one another?
Answer for images:  image_table
Question number: 49, Question JSON: question_7323.json, Question: In the movie where Ted McGinley played Dan Reed, how many men are shown on the cover?
Answer for images:  image_table
Question number: 50, Question JSON: question_16851.json, Question: When did 1st album of the red headed artist at the Parque Viva come out?
Answer for images:  image_text
Question number: 51, Question JSON: question_2526.json, Question: What date did the first episode of the show starring Jillian Claire as Abigail Deveraux air?
Answer for images:  text
Question number: 52, Question JSON: question_14005.json, Question: Was the accolade received by Natalie Wood latest in her career the Star of Tomorrow award or the Best Foreign actress award?
Answer for images:  table
Question number: 53, Question JSON: question_21958.json, Question: In which city was the band whose members wrote "Only the Young" formed?
Answer for images:  text
Question number: 54, Question JSON: question_3662.json, Question: What's the coat color of the writer of song for wachet auf (sleepers awake) and chorale text?
Answer for images:  image_text
Question number: 55, Question JSON: question_10399.json, Question: Which documentary is more recent in years in Documentaries of Robert De Niro filmography, More than a Movie or Biography: Liza Minnelli?
Answer for images:  table
Question number: 56, Question JSON: question_10125.json, Question: Which artist's song did Amylea sing in the semi finals of Akademi Fantasia during season 3?
Answer for images:  table
Question number: 57, Question JSON: question_9578.json, Question: Which film title did Dick Wesson act in first:  The title with a poster featuring a rocket or Calamity Jane?
Answer for images:  image_table
Question number: 58, Question JSON: question_19883.json, Question: Which NFL team with a logo featuring a human that lost to the Oakland Raiders in the 2017 season was also the team Roman Reigns played for?
Answer for images:  image_text
Question number: 59, Question JSON: question_6113.json, Question: What vehicle is Crash Bandicoot on the cover of the 1998 M. Mothersbaugh video game?
Answer for images:  image_table
Question number: 60, Question JSON: question_1138.json, Question: Was BK Derby or Djurgårdens IF, the one with lower points in Division 2 Östra of 1933–34 in Swedish football?
Answer for images:  table
Question number: 61, Question JSON: question_11373.json, Question: Among the Argentine football teams that were relegated in 1962, which team feature a single star above a crest on their logo?
Answer for images:  image_table
Question number: 62, Question JSON: question_8715.json, Question: Did winner of Master's two years in a row or Bernhard Langer have lower Order of Merit 1991 European Tour position?
Answer for images:  text_table
Question number: 63, Question JSON: question_22206.json, Question: Which location won a LEAF Award first:  Where they went it pitch perfect 2 or the location featuring a skyscraper with an open section by its roof, resembling a bottle opener?
Answer for images:  image_table
Question number: 64, Question JSON: question_16127.json, Question: What are the players wearing around their necks in this image from the 1998 Minnesota Vikings season?
Answer for images:  image
Question number: 65, Question JSON: question_19723.json, Question: in Los Angeles Chargers of List of NFL playoff games, when did the opponent that has a horse in logo, change their logo?
Answer for images:  text_table
Question number: 66, Question JSON: question_21696.json, Question: In the 2009 FC Rostov season transfers in, what was the from club for the undisclosed fee for the date March 9, 2009?
Answer for images:  table
Question number: 67, Question JSON: question_6883.json, Question: Does Hilary Duff sing in the movie where T.J. Thyne played the Emcee?
Answer for images:  text_table
Question number: 68, Question JSON: question_23720.json, Question: Was Toni Polster the Austrian Football Bundesliga top scorer in the 1981-82 season?
Answer for images:  table
Question number: 69, Question JSON: question_17225.json, Question: Which 1999 European Seniors tournament was hosted by the country dubbed "Celtic Tiger" by economists?
Answer for images:  text_table

In [17]:
# pk.dump(multimodal_unimodal_dataset, open("multimodal_unimodal_one_prompt.pk", "wb"))

In [20]:
multimodal_unimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,"[image, text]",image_table
1,question_13547.json,What object is seen in the center of the Days ...,66,Television,object depicted (center of poster),object,[image],image
2,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,"[text, table]",table
3,question_17634.json,Which location with red seating areas is where...,82,Sports,location (venue/stadium/track) with red seatin...,location,[image],image_table
4,question_6353.json,What team played the Seattle Seahawks in the 1...,169,Sports,NFL team (opponent team name),sports team,"[text, table]",text_table
...,...,...,...,...,...,...,...,...
65,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,"[image, text]",text_table
66,question_21696.json,"In the 2009 FC Rostov season transfers in, wha...",117,Sports,football (soccer) club name,organization,[table],table
67,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,"[table, text]",text_table
68,question_23720.json,Was Toni Polster the Austrian Football Bundesl...,83,Sports,yes/no (boolean),boolean,[table],table
69,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,"[text, table]",text_table

In [18]:
# multimodal_unimodal_dataset1 = pk.load(open("multimodal_unimodal_one_prompt.pk", "rb"))

In [23]:
multimodal_unimodal_dataset["modality"] = multimodal_unimodal_dataset["modality"].apply(lambda x: ["table"] if x == ['table', 'table'] else x)
multimodal_unimodal_dataset["modality"] = multimodal_unimodal_dataset["modality"].apply(normalize_combo)
multimodal_unimodal_dataset["modality_answers"] = multimodal_unimodal_dataset["modality_answers"].apply(normalize_combo)

In [24]:
multimodal_unimodal_dataset

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,image_text,image_table
1,question_13547.json,What object is seen in the center of the Days ...,66,Television,object depicted (center of poster),object,image,image
2,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,table_text,table
3,question_17634.json,Which location with red seating areas is where...,82,Sports,location (venue/stadium/track) with red seatin...,location,image,image_table
4,question_6353.json,What team played the Seattle Seahawks in the 1...,169,Sports,NFL team (opponent team name),sports team,table_text,table_text
...,...,...,...,...,...,...,...,...
65,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,image_text,table_text
66,question_21696.json,"In the 2009 FC Rostov season transfers in, wha...",117,Sports,football (soccer) club name,organization,table,table
67,question_6883.json,Does Hilary Duff sing in the movie where T.J. ...,69,Film,yes/no (whether Hilary Duff sings in a specifi...,boolean,table_text,table_text
68,question_23720.json,Was Toni Polster the Austrian Football Bundesl...,83,Sports,yes/no (boolean),boolean,table,table
69,question_17225.json,Which 1999 European Seniors tournament was hos...,101,Sports,European Seniors tournament (1999 edition),sports tournament,table_text,table_text

In [28]:
mask = multimodal_unimodal_dataset.apply(
    lambda row: (row["modality"] != row["modality_answers"]) and
                (len(set(row["modality"].split("_")).intersection(row["modality_answers"].split("_"))) > 0),
    axis=1
)

filtered = multimodal_unimodal_dataset[mask]

In [31]:
filtered

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,image_text,image_table
2,question_12447.json,"The song ""With a Flair"" was written for a 1971...",237,Film,character role (part played by an actor in a m...,role,table_text,table
3,question_17634.json,Which location with red seating areas is where...,82,Sports,location (venue/stadium/track) with red seatin...,location,image,image_table
7,question_17568.json,In the location out of surrey or london of kin...,116,Other,type of wheel,object type,image_text,image
32,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,image_text,table_text
46,question_8874.json,Which video game title was Danielle Nicolet a ...,178,Video games,video game title (the earlier of two compared ...,video game,image_text,image_table
48,question_14856.json,What are the names of the colosseum in the cit...,164,Buildings,names of a colosseum (building name or names),building,image_text,image_table
51,question_2526.json,What date did the first episode of the show st...,92,Television,air date (date of first episode),date,table_text,text
56,question_10125.json,Which artist's song did Amylea sing in the sem...,91,Television,artist (song original performer),person,table_text,table
61,question_11373.json,Among the Argentine football teams that were r...,125,Sports,Argentine football team (club) name,sports team,image,image_table
63,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,image_text,image_table
65,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,image_text,table_text

In [30]:
filtered[filtered["modality"] == "image_text"]

,index,original_question,question_length,question_topic,question_answer_class_specific,question_answer_class_general,modality,modality_answers
0,question_16282.json,The female artist with long brown hair extendi...,188,Music,person (guitarist),person,image_text,image_table
7,question_17568.json,In the location out of surrey or london of kin...,116,Other,type of wheel,object type,image_text,image
32,question_3021.json,What is the meaning of the colors of the flag ...,188,Sports,meanings/symbolism of flag colors,description,image_text,table_text
46,question_8874.json,Which video game title was Danielle Nicolet a ...,178,Video games,video game title (the earlier of two compared ...,video game,image_text,image_table
48,question_14856.json,What are the names of the colosseum in the cit...,164,Buildings,names of a colosseum (building name or names),building,image_text,image_table
63,question_22206.json,Which location won a LEAF Award first: Where ...,175,Film,location (place) that won a LEAF Award first,location,image_text,image_table
65,question_19723.json,in Los Angeles Chargers of List of NFL playoff...,120,Sports,date or year of a logo change,time,image_text,table_text

In [1]:
def calculate_metrics(dataset): 
    labels = sorted(set(dataset["modality"]))
    
    print(labels)
    
    results = {}
    
    for label in labels:
        tp = fp = fn = 0
        
        for _, row in dataset.iterrows():
            gt = row["modality"]
            pred = row["modality_answers"]
            
            if pred == label and gt == label:
                tp += 1
            elif pred == label and gt != label:
                fp += 1
            elif pred != label and gt == label:
                fn += 1
        
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall    = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1        = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0
        
        results[label] = {
            "TP": tp,
            "FP": fp,
            "FN": fn,
            "precision": precision,
            "recall": recall,
            "f1": f1
        }
        
    return results

In [131]:
results = calculate_metrics(multimodal_unimodal_dataset)

['image', 'image_table', 'image_text', 'table', 'table_text', 'text']

In [133]:
pd.DataFrame(results)

              image  image_table  image_text      table  table_text      text
TP         5.000000    14.000000    6.000000  14.000000   10.000000  7.000000
FP         1.000000     6.000000    0.000000   3.000000    3.000000  1.000000
FN         2.000000     0.000000    8.000000   0.000000    4.000000  0.000000
precision  0.833333     0.700000    1.000000   0.823529    0.769231  0.875000
recall     0.714286     1.000000    0.428571   1.000000    0.714286  1.000000
f1         0.769231     0.823529    0.600000   0.903226    0.740741  0.933333